// lib/areaData.ts

export interface AreaData {
  slug: string
  name: string
  county: string
  overview: string
  services: string[]
  landmarks: string[]
  whyChooseUs: string[]
  metaTitle: string
  metaDescription: string
}

export const areas: AreaData[] = [
  {
    slug: 'dallas',
    name: 'Dallas',
    county: 'Dallas County',
    overview:
      '2EZ TEK provides professional fitness equipment repair, assembly, and commercial gym maintenance throughout Dallas, TX. From luxury home gyms in Preston Hollow to apartment fitness centers in Uptown and commercial facilities across the city, our technicians service all major brands onsite.',
    services: [
      'Treadmill Repair Dallas',
      'Elliptical Repair Dallas',
      'Exercise Bike Repair Dallas',
      'Home Gym Assembly Dallas',
      'Commercial Gym Maintenance Dallas',
      'Strength Equipment Repair Dallas',
      'Cable Machine Repair Dallas',
      'Preventative Maintenance Dallas',
    ],
    landmarks: [
      'Uptown Dallas',
      'Preston Hollow',
      'Deep Ellum',
      'Oak Lawn',
      'North Dallas',
      'Downtown Dallas',
    ],
    whyChooseUs: [
      'Onsite repair throughout all of Dallas',
      'Same-day and next-day availability',
      'All major brands serviced',
      'Residential and commercial experience',
      'SmartGymOps-powered service tracking',
      '500+ five-star reviews',
    ],
    metaTitle: 'Fitness Equipment Repair Dallas TX | 2EZ TEK',
    metaDescription:
      'Professional fitness equipment repair in Dallas, TX. Treadmill repair, elliptical repair, gym assembly, and commercial maintenance. Call 2EZ TEK today.',
  },
  {
    slug: 'fort-worth',
    name: 'Fort Worth',
    county: 'Tarrant County',
    overview:
      '2EZ TEK provides expert fitness equipment repair and maintenance throughout Fort Worth, TX. Whether you need treadmill repair in Westover Hills, gym assembly in the Cultural District, or commercial maintenance for a Fort Worth fitness facility, our technicians are ready.',
    services: [
      'Treadmill Repair Fort Worth',
      'Elliptical Repair Fort Worth',
      'Exercise Bike Repair Fort Worth',
      'Home Gym Assembly Fort Worth',
      'Commercial Gym Maintenance Fort Worth',
      'Strength Equipment Repair Fort Worth',
      'Cable Machine Repair Fort Worth',
      'Preventative Maintenance Fort Worth',
    ],
    landmarks: [
      'Westover Hills',
      'Cultural District',
      'Sundance Square',
      'TCU Area',
      'Alliance Corridor',
      'Tanglewood',
    ],
    whyChooseUs: [
      'Serving all of Fort Worth and Tarrant County',
      'Residential and commercial clients',
      'All major equipment brands',
      'Fast turnaround on most repairs',
      'SmartGymOps service documentation',
      '500+ five-star reviews across DFW',
    ],
    metaTitle: 'Fitness Equipment Repair Fort Worth TX | 2EZ TEK',
    metaDescription:
      'Professional fitness equipment repair in Fort Worth, TX. Treadmill repair, gym assembly, and commercial maintenance by 2EZ TEK. Call today.',
  },
  {
    slug: 'plano',
    name: 'Plano',
    county: 'Collin County',
    overview:
      '2EZ TEK services fitness equipment throughout Plano, TX, one of the most active fitness communities in the DFW area. From home gym setups in West Plano to apartment fitness centers and corporate gym maintenance, our technicians provide fast, professional onsite service.',
    services: [
      'Treadmill Repair Plano',
      'Elliptical Repair Plano',
      'Exercise Bike Repair Plano',
      'Home Gym Assembly Plano',
      'Commercial Gym Maintenance Plano',
      'Strength Equipment Repair Plano',
      'Cable Machine Repair Plano',
      'Preventative Maintenance Plano',
    ],
    landmarks: [
      'West Plano',
      'Legacy Business District',
      'Willow Bend',
      'East Plano',
      'Downtown Plano',
      'Plano Parkway Corridor',
    ],
    whyChooseUs: [
      'Serving all of Plano and Collin County',
      'Same-day availability in most cases',
      'Luxury home gym specialists',
      'Corporate and apartment fitness centers',
      'SmartGymOps service tracking',
      '500+ five-star reviews',
    ],
    metaTitle: 'Fitness Equipment Repair Plano TX | 2EZ TEK',
    metaDescription:
      'Fitness equipment repair in Plano, TX. Treadmill repair, elliptical service, home gym assembly, and commercial maintenance by 2EZ TEK.',
  },
  {
    slug: 'frisco',
    name: 'Frisco',
    county: 'Collin County',
    overview:
      '2EZ TEK provides premium fitness equipment repair and installation services throughout Frisco, TX. One of the fastest-growing cities in America, Frisco is home to luxury residential communities, world-class sports facilities, and high-end fitness centers, all of which we proudly service.',
    services: [
      'Treadmill Repair Frisco',
      'Elliptical Repair Frisco',
      'Exercise Bike Repair Frisco',
      'Home Gym Assembly Frisco',
      'Commercial Gym Maintenance Frisco',
      'Strength Equipment Repair Frisco',
      'Cable Machine Repair Frisco',
      'Preventative Maintenance Frisco',
    ],
    landmarks: [
      'The Star District',
      'Frisco Square',
      'Wade Park',
      'Newman Village',
      'Starwood',
      'Stonebriar Corridor',
    ],
    whyChooseUs: [
      'Serving all of Frisco and surrounding areas',
      'Luxury home gym installation specialists',
      'Commercial and residential experience',
      'All major brands serviced',
      'SmartGymOps-powered tracking',
      '500+ five-star reviews across DFW',
    ],
    metaTitle: 'Fitness Equipment Repair Frisco TX | 2EZ TEK',
    metaDescription:
      'Fitness equipment repair in Frisco, TX. Treadmill repair, home gym assembly, and commercial maintenance by 2EZ TEK. Book your service today.',
  },
  {
    slug: 'irving',
    name: 'Irving',
    county: 'Dallas County',
    overview:
      '2EZ TEK services fitness equipment throughout Irving, TX, including the Las Colinas urban center, hotel fitness centers along the Airport Freeway corridor, and residential communities across the city. We provide fast onsite repair and maintenance for all major brands.',
    services: [
      'Treadmill Repair Irving',
      'Elliptical Repair Irving',
      'Exercise Bike Repair Irving',
      'Home Gym Assembly Irving',
      'Commercial Gym Maintenance Irving',
      'Hotel Fitness Center Maintenance Irving',
      'Strength Equipment Repair Irving',
      'Preventative Maintenance Irving',
    ],
    landmarks: [
      'Las Colinas',
      'Valley Ranch',
      'Irving Convention Center',
      'DFW Airport Corridor',
      'Hackberry Creek',
      'Los Colinas Urban Center',
    ],
    whyChooseUs: [
      'Hotel and hospitality fitness center specialists',
      'Corporate campus gym maintenance',
      'Serving all of Irving and Las Colinas',
      'All major brands serviced',
      'SmartGymOps service tracking',
      '500+ five-star reviews',
    ],
    metaTitle: 'Fitness Equipment Repair Irving TX | 2EZ TEK',
    metaDescription:
      'Fitness equipment repair in Irving, TX. Hotel fitness centers, home gyms, and commercial maintenance by 2EZ TEK. Las Colinas and all of Irving.',
  },
  {
    slug: 'arlington',
    name: 'Arlington',
    county: 'Tarrant County',
    overview:
      '2EZ TEK provides expert fitness equipment repair and maintenance throughout Arlington, TX. Home to AT&T Stadium, Globe Life Field, and a thriving fitness community, Arlington is a key service market for 2EZ TEK, from apartment fitness centers near UT Arlington to commercial gyms across the city.',
    services: [
      'Treadmill Repair Arlington',
      'Elliptical Repair Arlington',
      'Exercise Bike Repair Arlington',
      'Home Gym Assembly Arlington',
      'Commercial Gym Maintenance Arlington',
      'Strength Equipment Repair Arlington',
      'Cable Machine Repair Arlington',
      'Preventative Maintenance Arlington',
    ],
    landmarks: [
      'Entertainment District',
      'UT Arlington Area',
      'Viridian',
      'Pantego',
      'North Arlington',
      'Dalworthington Gardens',
    ],
    whyChooseUs: [
      'Serving all of Arlington and mid-cities',
      'Commercial and residential clients',
      'All major equipment brands',
      'Fast response times',
      'SmartGymOps documentation',
      '500+ five-star reviews',
    ],
    metaTitle: 'Fitness Equipment Repair Arlington TX | 2EZ TEK',
    metaDescription:
      'Fitness equipment repair in Arlington, TX. Treadmill repair, elliptical service, and commercial gym maintenance by 2EZ TEK. Book today.',
  },
  {
    slug: 'richardson',
    name: 'Richardson',
    county: 'Dallas County',
    overview:
      '2EZ TEK services fitness equipment throughout Richardson, TX, a growing tech hub with a strong residential fitness culture. From home gym setups near UTD to apartment fitness centers and corporate wellness rooms in the Telecom Corridor, we provide fast professional service.',
    services: [
      'Treadmill Repair Richardson',
      'Elliptical Repair Richardson',
      'Exercise Bike Repair Richardson',
      'Home Gym Assembly Richardson',
      'Commercial Gym Maintenance Richardson',
      'Strength Equipment Repair Richardson',
      'Corporate Gym Maintenance Richardson',
      'Preventative Maintenance Richardson',
    ],
    landmarks: [
      'Telecom Corridor',
      'UTD Area',
      'Spring Valley',
      'Canyon Creek',
      'Arapaho Road Corridor',
      'Downtown Richardson',
    ],
    whyChooseUs: [
      'Corporate and tech campus gym specialists',
      'Serving all of Richardson',
      'Residential and commercial experience',
      'All major brands serviced',
      'SmartGymOps service tracking',
      '500+ five-star reviews',
    ],
    metaTitle: 'Fitness Equipment Repair Richardson TX | 2EZ TEK',
    metaDescription:
      'Fitness equipment repair in Richardson, TX. Treadmill repair, home gym assembly, and corporate gym maintenance by 2EZ TEK.',
  },
  {
    slug: 'mckinney',
    name: 'McKinney',
    county: 'Collin County',
    overview:
      '2EZ TEK provides professional fitness equipment repair and installation throughout McKinney, TX. One of the top-ranked cities to live in America, McKinney is home to luxury residential communities and growing commercial fitness facilities, all of which we proudly service.',
    services: [
      'Treadmill Repair McKinney',
      'Elliptical Repair McKinney',
      'Exercise Bike Repair McKinney',
      'Home Gym Assembly McKinney',
      'Commercial Gym Maintenance McKinney',
      'Strength Equipment Repair McKinney',
      'Cable Machine Repair McKinney',
      'Preventative Maintenance McKinney',
    ],
    landmarks: [
      'Historic Downtown McKinney',
      'Craig Ranch',
      'Stonebridge Ranch',
      'Eldorado Parkway Corridor',
      'Adriatica Village',
      'West McKinney',
    ],
    whyChooseUs: [
      'Luxury home gym specialists',
      'Serving all of McKinney and Collin County',
      'Residential and commercial experience',
      'All major brands serviced',
      'SmartGymOps tracking',
      '500+ five-star reviews',
    ],
    metaTitle: 'Fitness Equipment Repair McKinney TX | 2EZ TEK',
    metaDescription:
      'Fitness equipment repair in McKinney, TX. Treadmill repair, home gym installation, and commercial maintenance by 2EZ TEK.',
  },
  {
    slug: 'garland',
    name: 'Garland',
    county: 'Dallas County',
    overview:
      '2EZ TEK services fitness equipment throughout Garland, TX. From residential treadmill repairs to apartment fitness center maintenance, our technicians provide fast, professional onsite service across all of Garland and the surrounding area.',
    services: [
      'Treadmill Repair Garland',
      'Elliptical Repair Garland',
      'Exercise Bike Repair Garland',
      'Home Gym Assembly Garland',
      'Commercial Gym Maintenance Garland',
      'Strength Equipment Repair Garland',
      'Cable Machine Repair Garland',
      'Preventative Maintenance Garland',
    ],
    landmarks: [
      'Downtown Garland',
      'Firewheel Town Center',
      'Duck Creek',
      'North Garland',
      'Sachse border area',
      'Rowlett Road Corridor',
    ],
    whyChooseUs: [
      'Serving all of Garland and East Dallas County',
      'Residential and commercial clients',
      'All major equipment brands',
      'Fast response times',
      'SmartGymOps service documentation',
      '500+ five-star reviews',
    ],
    metaTitle: 'Fitness Equipment Repair Garland TX | 2EZ TEK',
    metaDescription:
      'Fitness equipment repair in Garland, TX. Treadmill repair, elliptical service, and commercial gym maintenance by 2EZ TEK.',
  },
  {
    slug: 'mesquite',
    name: 'Mesquite',
    county: 'Dallas County',
    overview:
      '2EZ TEK provides professional fitness equipment repair and maintenance throughout Mesquite, TX. From home gym setups to apartment fitness centers and commercial facilities, our technicians deliver fast onsite service across all of Mesquite.',
    services: [
      'Treadmill Repair Mesquite',
      'Elliptical Repair Mesquite',
      'Exercise Bike Repair Mesquite',
      'Home Gym Assembly Mesquite',
      'Commercial Gym Maintenance Mesquite',
      'Strength Equipment Repair Mesquite',
      'Cable Machine Repair Mesquite',
      'Preventative Maintenance Mesquite',
    ],
    landmarks: [
      'Downtown Mesquite',
      'Mesquite Rodeo Area',
      'Skyline Area',
      'North Mesquite',
      'Town East Corridor',
      'Mesquite Metro Area',
    ],
    whyChooseUs: [
      'Serving all of Mesquite and Southeast Dallas County',
      'Residential and commercial experience',
      'All major brands serviced',
      'Fast turnaround',
      'SmartGymOps tracking',
      '500+ five-star reviews',
    ],
    metaTitle: 'Fitness Equipment Repair Mesquite TX | 2EZ TEK',
    metaDescription:
      'Fitness equipment repair in Mesquite, TX. Treadmill repair, home gym assembly, and commercial maintenance by 2EZ TEK. Call today.',
  },
  {
    slug: 'carrollton',
    name: 'Carrollton',
    county: 'Dallas County',
    overview:
      '2EZ TEK services fitness equipment throughout Carrollton, TX. Centrally located between Dallas and Denton, Carrollton is home to a diverse mix of residential communities and commercial fitness facilities, all served by our professional onsite repair and maintenance team.',
    services: [
      'Treadmill Repair Carrollton',
      'Elliptical Repair Carrollton',
      'Exercise Bike Repair Carrollton',
      'Home Gym Assembly Carrollton',
      'Commercial Gym Maintenance Carrollton',
      'Strength Equipment Repair Carrollton',
      'Cable Machine Repair Carrollton',
      'Preventative Maintenance Carrollton',
    ],
    landmarks: [
      'Downtown Carrollton',
      'Addison border area',
      'Frankford Road Corridor',
      'Old Town Carrollton',
      'Josey Ranch',
      'North Carrollton',
    ],
    whyChooseUs: [
      'Serving all of Carrollton and North Dallas County',
      'Residential and commercial clients',
      'All major equipment brands',
      'SmartGymOps service tracking',
      'Fast response times',
      '500+ five-star reviews',
    ],
    metaTitle: 'Fitness Equipment Repair Carrollton TX | 2EZ TEK',
    metaDescription:
      'Fitness equipment repair in Carrollton, TX. Treadmill repair, gym assembly, and commercial maintenance by 2EZ TEK. Book your service today.',
  },
  {
    slug: 'addison',
    name: 'Addison',
    county: 'Dallas County',
    overview:
      '2EZ TEK provides premium fitness equipment repair and maintenance throughout Addison, TX. Known for its restaurant row, corporate offices, and upscale apartments, Addison is a high-demand market for professional fitness equipment service, and 2EZ TEK delivers.',
    services: [
      'Treadmill Repair Addison',
      'Elliptical Repair Addison',
      'Exercise Bike Repair Addison',
      'Home Gym Assembly Addison',
      'Commercial Gym Maintenance Addison',
      'Hotel Fitness Center Maintenance Addison',
      'Apartment Gym Maintenance Addison',
      'Preventative Maintenance Addison',
    ],
    landmarks: [
      'Addison Circle',
      'Belt Line Road Corridor',
      'Vitruvian Park',
      'Addison Airport Area',
      'Quorum Drive Corridor',
      'North Dallas Tollway Area',
    ],
    whyChooseUs: [
      'Hotel and apartment gym specialists',
      'Serving all of Addison',
      'Corporate and residential experience',
      'All major brands serviced',
      'SmartGymOps service tracking',
      '500+ five-star reviews',
    ],
    metaTitle: 'Fitness Equipment Repair Addison TX | 2EZ TEK',
    metaDescription:
      'Fitness equipment repair in Addison, TX. Hotel fitness centers, apartment gyms, and home gym service by 2EZ TEK. Call today.',
  },
  {
    slug: 'allen',
    name: 'Allen',
    county: 'Collin County',
    overview:
      '2EZ TEK provides professional fitness equipment repair and installation throughout Allen, TX. One of the most sought-after communities in Collin County, Allen is home to high-end residential neighborhoods, luxury apartment complexes, and growing commercial fitness facilities, all serviced by our experienced technicians.',
    services: [
      'Treadmill Repair Allen',
      'Elliptical Repair Allen',
      'Exercise Bike Repair Allen',
      'Home Gym Assembly Allen',
      'Commercial Gym Maintenance Allen',
      'Strength Equipment Repair Allen',
      'Cable Machine Repair Allen',
      'Preventative Maintenance Allen',
    ],
    landmarks: [
      'Allen Premium Outlets Area',
      'Twin Creeks',
      'Watters Creek',
      'Montgomery Farm',
      'Allen Station Park Area',
      'Stacy Road Corridor',
    ],
    whyChooseUs: [
      'Serving all of Allen and North Collin County',
      'Luxury home gym specialists',
      'Residential and apartment complex experience',
      'All major brands serviced',
      'SmartGymOps service tracking',
      '500+ five-star reviews across DFW',
    ],
    metaTitle: 'Fitness Equipment Repair Allen TX | 2EZ TEK',
    metaDescription:
      'Fitness equipment repair in Allen, TX. Treadmill repair, home gym assembly, and commercial maintenance by 2EZ TEK. Call today.',
  },
  {
    slug: 'lewisville',
    name: 'Lewisville',
    county: 'Denton County',
    overview:
      '2EZ TEK services fitness equipment throughout Lewisville, TX. Strategically located near Lake Lewisville and the DFW metroplex core, Lewisville is home to diverse residential communities, apartment fitness centers, and commercial facilities that rely on our fast, professional onsite repair service.',
    services: [
      'Treadmill Repair Lewisville',
      'Elliptical Repair Lewisville',
      'Exercise Bike Repair Lewisville',
      'Home Gym Assembly Lewisville',
      'Commercial Gym Maintenance Lewisville',
      'Strength Equipment Repair Lewisville',
      'Apartment Gym Maintenance Lewisville',
      'Preventative Maintenance Lewisville',
    ],
    landmarks: [
      'Lake Lewisville Area',
      'Old Town Lewisville',
      'Vista Ridge Corridor',
      'Hebron Parkway Area',
      'Castle Hills',
      'South Lewisville',
    ],
    whyChooseUs: [
      'Serving all of Lewisville and Denton County',
      'Apartment and residential complex specialists',
      'All major equipment brands',
      'Fast response times',
      'SmartGymOps documentation',
      '500+ five-star reviews',
    ],
    metaTitle: 'Fitness Equipment Repair Lewisville TX | 2EZ TEK',
    metaDescription:
      'Fitness equipment repair in Lewisville, TX. Treadmill repair, elliptical service, and commercial gym maintenance by 2EZ TEK. Book today.',
  },
  {
    slug: 'grand-prairie',
    name: 'Grand Prairie',
    county: 'Dallas County',
    overview:
      '2EZ TEK provides expert fitness equipment repair and maintenance throughout Grand Prairie, TX. Situated between Dallas and Fort Worth, Grand Prairie is a large, diverse city with a growing residential fitness market and a strong commercial sector. Our technicians provide fast onsite service across all of Grand Prairie.',
    services: [
      'Treadmill Repair Grand Prairie',
      'Elliptical Repair Grand Prairie',
      'Exercise Bike Repair Grand Prairie',
      'Home Gym Assembly Grand Prairie',
      'Commercial Gym Maintenance Grand Prairie',
      'Strength Equipment Repair Grand Prairie',
      'Cable Machine Repair Grand Prairie',
      'Preventative Maintenance Grand Prairie',
    ],
    landmarks: [
      'Epic Waters Area',
      'Lynn Creek Marina',
      'Lone Star Park Area',
      'Great Southwest Industrial District',
      'West Grand Prairie',
      'Fish Creek Corridor',
    ],
    whyChooseUs: [
      'Serving all of Grand Prairie, Dallas and Tarrant County',
      'Residential and commercial experience',
      'All major equipment brands',
      'Fast turnaround on most repairs',
      'SmartGymOps tracking',
      '500+ five-star reviews',
    ],
    metaTitle: 'Fitness Equipment Repair Grand Prairie TX | 2EZ TEK',
    metaDescription:
      'Fitness equipment repair in Grand Prairie, TX. Treadmill repair, home gym assembly, and commercial maintenance by 2EZ TEK.',
  },
  {
    slug: 'flower-mound',
    name: 'Flower Mound',
    county: 'Denton County',
    overview:
      '2EZ TEK services fitness equipment throughout Flower Mound, TX. An affluent master-planned community with a strong fitness culture, Flower Mound is home to high-end home gyms, luxury apartment complexes, and growing commercial facilities. Our technicians deliver white-glove service across the entire area.',
    services: [
      'Treadmill Repair Flower Mound',
      'Elliptical Repair Flower Mound',
      'Exercise Bike Repair Flower Mound',
      'Home Gym Assembly Flower Mound',
      'Commercial Gym Maintenance Flower Mound',
      'Strength Equipment Repair Flower Mound',
      'Cable Machine Repair Flower Mound',
      'Preventative Maintenance Flower Mound',
    ],
    landmarks: [
      'Lakeside Business District',
      'River Walk at Central Park',
      'Grapevine Lake Area',
      'Bridlewood',
      'Wellington',
      'FM 2499 Corridor',
    ],
    whyChooseUs: [
      'Luxury home gym specialists',
      'Serving all of Flower Mound and Denton County',
      'White-glove installation and repair',
      'All major brands serviced',
      'SmartGymOps service tracking',
      '500+ five-star reviews',
    ],
    metaTitle: 'Fitness Equipment Repair Flower Mound TX | 2EZ TEK',
    metaDescription:
      'Fitness equipment repair in Flower Mound, TX. Treadmill repair, luxury home gym installation, and commercial maintenance by 2EZ TEK.',
  },
  {
    slug: 'southlake',
    name: 'Southlake',
    county: 'Tarrant County',
    overview:
      '2EZ TEK provides premium fitness equipment repair and installation throughout Southlake, TX. One of the most affluent communities in Texas, Southlake is home to high-end residential properties with elaborate home gyms, luxury fitness studios, and premium equipment that demands expert care.',
    services: [
      'Treadmill Repair Southlake',
      'Elliptical Repair Southlake',
      'Exercise Bike Repair Southlake',
      'Home Gym Assembly Southlake',
      'Commercial Gym Maintenance Southlake',
      'Luxury Home Gym Installation Southlake',
      'Strength Equipment Repair Southlake',
      'Preventative Maintenance Southlake',
    ],
    landmarks: [
      'Southlake Town Square',
      'Timarron',
      'Shady Oaks',
      'Carillon',
      'Westlake Border Area',
      'North Carroll Avenue Corridor',
    ],
    whyChooseUs: [
      'Premium service for high-end residential clients',
      'Luxury home gym installation specialists',
      'Serving Southlake and Carroll ISD area',
      'All major brands including Peloton, NordicTrack, Life Fitness',
      'SmartGymOps service documentation',
      '500+ five-star reviews',
    ],
    metaTitle: 'Fitness Equipment Repair Southlake TX | 2EZ TEK',
    metaDescription:
      'Fitness equipment repair in Southlake, TX. Premium home gym installation, treadmill repair, and equipment maintenance by 2EZ TEK.',
  },
  {
    slug: 'coppell',
    name: 'Coppell',
    county: 'Dallas County',
    overview:
      '2EZ TEK services fitness equipment throughout Coppell, TX. Known for its outstanding schools, family-oriented neighborhoods, and proximity to DFW Airport, Coppell is home to a strong residential fitness market and a growing number of commercial facilities. Our technicians provide fast professional service across all of Coppell.',
    services: [
      'Treadmill Repair Coppell',
      'Elliptical Repair Coppell',
      'Exercise Bike Repair Coppell',
      'Home Gym Assembly Coppell',
      'Commercial Gym Maintenance Coppell',
      'Strength Equipment Repair Coppell',
      'Cable Machine Repair Coppell',
      'Preventative Maintenance Coppell',
    ],
    landmarks: [
      'Old Town Coppell',
      'DFW Airport North Corridor',
      'Riverchase',
      'Moore Road Corridor',
      'Coppell Ranch',
      'MacArthur Corridor',
    ],
    whyChooseUs: [
      'Serving all of Coppell and Northwest Dallas County',
      'Residential and commercial experience',
      'All major equipment brands',
      'Fast response times',
      'SmartGymOps tracking',
      '500+ five-star reviews',
    ],
    metaTitle: 'Fitness Equipment Repair Coppell TX | 2EZ TEK',
    metaDescription:
      'Fitness equipment repair in Coppell, TX. Treadmill repair, home gym assembly, and commercial maintenance by 2EZ TEK. Call today.',
  },
  {
    slug: 'grapevine',
    name: 'Grapevine',
    county: 'Tarrant County',
    overview:
      '2EZ TEK provides professional fitness equipment repair and maintenance throughout Grapevine, TX. Adjacent to DFW Airport and Lake Grapevine, Grapevine is home to hotels, corporate properties, luxury residential communities, and commercial fitness facilities that all benefit from our expert onsite service.',
    services: [
      'Treadmill Repair Grapevine',
      'Elliptical Repair Grapevine',
      'Exercise Bike Repair Grapevine',
      'Home Gym Assembly Grapevine',
      'Hotel Fitness Center Maintenance Grapevine',
      'Commercial Gym Maintenance Grapevine',
      'Strength Equipment Repair Grapevine',
      'Preventative Maintenance Grapevine',
    ],
    landmarks: [
      'Historic Downtown Grapevine',
      'Grapevine Lake Area',
      'DFW Airport South Corridor',
      'Gaylord Texan Area',
      'Vineyards',
      'Silver Lake',
    ],
    whyChooseUs: [
      'Hotel and hospitality fitness center specialists',
      'Serving all of Grapevine and Tarrant County',
      'Residential and commercial experience',
      'All major brands serviced',
      'SmartGymOps service tracking',
      '500+ five-star reviews',
    ],
    metaTitle: 'Fitness Equipment Repair Grapevine TX | 2EZ TEK',
    metaDescription:
      'Fitness equipment repair in Grapevine, TX. Hotel fitness centers, home gyms, and commercial maintenance by 2EZ TEK. Call today.',
  },
  {
    slug: 'keller',
    name: 'Keller',
    county: 'Tarrant County',
    overview:
      '2EZ TEK services fitness equipment throughout Keller, TX. A sought-after residential community in northeast Tarrant County, Keller is known for top-rated schools, executive neighborhoods, and a high concentration of home gyms and premium fitness equipment. Our technicians are ready to serve.',
    services: [
      'Treadmill Repair Keller',
      'Elliptical Repair Keller',
      'Exercise Bike Repair Keller',
      'Home Gym Assembly Keller',
      'Commercial Gym Maintenance Keller',
      'Strength Equipment Repair Keller',
      'Cable Machine Repair Keller',
      'Preventative Maintenance Keller',
    ],
    landmarks: [
      'Old Town Keller',
      'Bear Creek Parkway Corridor',
      'Hidden Lakes',
      'Keller Town Center',
      'Hollow Brook',
      'Johnson Road Area',
    ],
    whyChooseUs: [
      'Luxury home gym specialists',
      'Serving all of Keller and Northeast Tarrant County',
      'Residential and commercial experience',
      'All major brands serviced',
      'SmartGymOps tracking',
      '500+ five-star reviews',
    ],
    metaTitle: 'Fitness Equipment Repair Keller TX | 2EZ TEK',
    metaDescription:
      'Fitness equipment repair in Keller, TX. Treadmill repair, home gym assembly, and commercial maintenance by 2EZ TEK.',
  },
  {
    slug: 'north-richland-hills',
    name: 'North Richland Hills',
    county: 'Tarrant County',
    overview:
      '2EZ TEK provides expert fitness equipment repair and maintenance throughout North Richland Hills, TX. A major mid-cities hub between Dallas and Fort Worth, NRH is home to a strong mix of residential communities, apartment complexes, and commercial fitness facilities that rely on our fast onsite service.',
    services: [
      'Treadmill Repair North Richland Hills',
      'Elliptical Repair North Richland Hills',
      'Exercise Bike Repair North Richland Hills',
      'Home Gym Assembly North Richland Hills',
      'Commercial Gym Maintenance North Richland Hills',
      'Strength Equipment Repair North Richland Hills',
      'Apartment Gym Maintenance North Richland Hills',
      'Preventative Maintenance North Richland Hills',
    ],
    landmarks: [
      'NRH Centre Area',
      'Iron Horse Golf Corridor',
      'Boulevard 26',
      'Fossil Creek Area',
      'North Tarrant Parkway Corridor',
      'Smithfield Area',
    ],
    whyChooseUs: [
      'Serving all of NRH and Mid-Cities Tarrant County',
      'Apartment and residential complex specialists',
      'All major equipment brands',
      'Fast response times',
      'SmartGymOps service documentation',
      '500+ five-star reviews',
    ],
    metaTitle: 'Fitness Equipment Repair North Richland Hills TX | 2EZ TEK',
    metaDescription:
      'Fitness equipment repair in North Richland Hills, TX. Treadmill repair, gym assembly, and commercial maintenance by 2EZ TEK.',
  },
  {
    slug: 'mansfield',
    name: 'Mansfield',
    county: 'Tarrant County',
    overview:
      '2EZ TEK services fitness equipment throughout Mansfield, TX. One of the fastest-growing cities in Tarrant County, Mansfield is attracting new residential communities, fitness studios, and commercial facilities that all require professional equipment service. Our technicians deliver fast, reliable onsite repair.',
    services: [
      'Treadmill Repair Mansfield',
      'Elliptical Repair Mansfield',
      'Exercise Bike Repair Mansfield',
      'Home Gym Assembly Mansfield',
      'Commercial Gym Maintenance Mansfield',
      'Strength Equipment Repair Mansfield',
      'Cable Machine Repair Mansfield',
      'Preventative Maintenance Mansfield',
    ],
    landmarks: [
      'Historic Downtown Mansfield',
      'Walnut Creek Country Club Area',
      'South Tarrant Parkway',
      'Broad Street Corridor',
      'Heritage High School Area',
      'West Mansfield',
    ],
    whyChooseUs: [
      'Serving all of Mansfield and South Tarrant County',
      'Residential and commercial experience',
      'All major equipment brands',
      'SmartGymOps service tracking',
      'Fast response times',
      '500+ five-star reviews',
    ],
    metaTitle: 'Fitness Equipment Repair Mansfield TX | 2EZ TEK',
    metaDescription:
      'Fitness equipment repair in Mansfield, TX. Treadmill repair, home gym assembly, and commercial maintenance by 2EZ TEK. Call today.',
  },
  {
    slug: 'denton',
    name: 'Denton',
    county: 'Denton County',
    overview:
      '2EZ TEK provides professional fitness equipment repair and maintenance throughout Denton, TX. Home to the University of North Texas and Texas Woman\'s University, Denton has a large fitness equipment market spanning university facilities, apartment complexes, commercial gyms, and residential clients across the city.',
    services: [
      'Treadmill Repair Denton',
      'Elliptical Repair Denton',
      'Exercise Bike Repair Denton',
      'Home Gym Assembly Denton',
      'Commercial Gym Maintenance Denton',
      'University Facility Gym Service Denton',
      'Strength Equipment Repair Denton',
      'Preventative Maintenance Denton',
    ],
    landmarks: [
      'University of North Texas Area',
      'Texas Woman\'s University Area',
      'Denton Square',
      'Rayzor Ranch',
      'Loop 288 Corridor',
      'South Denton',
    ],
    whyChooseUs: [
      'Serving all of Denton and Denton County',
      'University and institutional facility experience',
      'Residential and commercial clients',
      'All major equipment brands',
      'SmartGymOps documentation',
      '500+ five-star reviews',
    ],
    metaTitle: 'Fitness Equipment Repair Denton TX | 2EZ TEK',
    metaDescription:
      'Fitness equipment repair in Denton, TX. Treadmill repair, commercial gym maintenance, and home gym assembly by 2EZ TEK.',
  },
  {
    slug: 'the-colony',
    name: 'The Colony',
    county: 'Denton County',
    overview:
      '2EZ TEK services fitness equipment throughout The Colony, TX. Bordering Frisco and Lake Lewisville, The Colony is a growing community with luxury residential developments, vibrant retail districts, and a strong demand for professional fitness equipment service.',
    services: [
      'Treadmill Repair The Colony',
      'Elliptical Repair The Colony',
      'Exercise Bike Repair The Colony',
      'Home Gym Assembly The Colony',
      'Commercial Gym Maintenance The Colony',
      'Strength Equipment Repair The Colony',
      'Cable Machine Repair The Colony',
      'Preventative Maintenance The Colony',
    ],
    landmarks: [
      'Nebraska Furniture Mart Area',
      'Lake Lewisville Shore',
      'Grandscape',
      'Memorial Drive Corridor',
      'Stewart Creek',
      'North Colony Blvd Area',
    ],
    whyChooseUs: [
      'Serving The Colony and South Denton County',
      'Residential and commercial experience',
      'All major equipment brands',
      'Fast response times',
      'SmartGymOps tracking',
      '500+ five-star reviews',
    ],
    metaTitle: 'Fitness Equipment Repair The Colony TX | 2EZ TEK',
    metaDescription:
      'Fitness equipment repair in The Colony, TX. Treadmill repair, home gym assembly, and commercial maintenance by 2EZ TEK.',
  },
  {
    slug: 'rowlett',
    name: 'Rowlett',
    county: 'Dallas County',
    overview:
      '2EZ TEK provides professional fitness equipment repair and maintenance throughout Rowlett, TX. Located along the eastern shore of Lake Ray Hubbard, Rowlett is a growing community with established neighborhoods, new residential developments, and a fitness market that demands fast, reliable service.',
    services: [
      'Treadmill Repair Rowlett',
      'Elliptical Repair Rowlett',
      'Exercise Bike Repair Rowlett',
      'Home Gym Assembly Rowlett',
      'Commercial Gym Maintenance Rowlett',
      'Strength Equipment Repair Rowlett',
      'Cable Machine Repair Rowlett',
      'Preventative Maintenance Rowlett',
    ],
    landmarks: [
      'Lake Ray Hubbard Shore',
      'Sapphire Bay Development',
      'Rowlett Road Corridor',
      'Main Street District',
      'Liberty Grove',
      'Waterview',
    ],
    whyChooseUs: [
      'Serving all of Rowlett and East Dallas County',
      'Residential and commercial clients',
      'All major equipment brands',
      'Fast response times',
      'SmartGymOps documentation',
      '500+ five-star reviews',
    ],
    metaTitle: 'Fitness Equipment Repair Rowlett TX | 2EZ TEK',
    metaDescription:
      'Fitness equipment repair in Rowlett, TX. Treadmill repair, home gym assembly, and commercial maintenance by 2EZ TEK.',
  },
  {
    slug: 'desoto',
    name: 'DeSoto',
    county: 'Dallas County',
    overview:
      '2EZ TEK services fitness equipment throughout DeSoto, TX. A thriving southern Dallas County community with a strong residential base and growing commercial sector, DeSoto is a key service area for 2EZ TEK. Our technicians provide fast professional onsite repair and maintenance for all equipment types.',
    services: [
      'Treadmill Repair DeSoto',
      'Elliptical Repair DeSoto',
      'Exercise Bike Repair DeSoto',
      'Home Gym Assembly DeSoto',
      'Commercial Gym Maintenance DeSoto',
      'Strength Equipment Repair DeSoto',
      'Cable Machine Repair DeSoto',
      'Preventative Maintenance DeSoto',
    ],
    landmarks: [
      'DeSoto Town Center',
      'Hampton Road Corridor',
      'Belt Line Road Corridor',
      'Westmoreland Area',
      'North DeSoto',
      'Hampton Inn Corridor',
    ],
    whyChooseUs: [
      'Serving all of DeSoto and Southern Dallas County',
      'Residential and commercial experience',
      'All major equipment brands',
      'Fast response times',
      'SmartGymOps service tracking',
      '500+ five-star reviews',
    ],
    metaTitle: 'Fitness Equipment Repair DeSoto TX | 2EZ TEK',
    metaDescription:
      'Fitness equipment repair in DeSoto, TX. Treadmill repair, home gym assembly, and commercial maintenance by 2EZ TEK. Call today.',
  },
  {
    slug: 'cedar-hill',
    name: 'Cedar Hill',
    county: 'Dallas County',
    overview:
      '2EZ TEK provides expert fitness equipment repair and maintenance throughout Cedar Hill, TX. Nestled southwest of Dallas with growing residential communities and a strong local fitness culture, Cedar Hill is an expanding market for professional fitness equipment service.',
    services: [
      'Treadmill Repair Cedar Hill',
      'Elliptical Repair Cedar Hill',
      'Exercise Bike Repair Cedar Hill',
      'Home Gym Assembly Cedar Hill',
      'Commercial Gym Maintenance Cedar Hill',
      'Strength Equipment Repair Cedar Hill',
      'Cable Machine Repair Cedar Hill',
      'Preventative Maintenance Cedar Hill',
    ],
    landmarks: [
      'Cedar Hill State Park Area',
      'Hillside Village',
      'FM 1382 Corridor',
      'Cedar Hill Town Center',
      'Pleasant Run Road Area',
      'West Cedar Hill',
    ],
    whyChooseUs: [
      'Serving all of Cedar Hill and Southwest Dallas County',
      'Residential and commercial experience',
      'All major equipment brands',
      'SmartGymOps tracking',
      'Fast response times',
      '500+ five-star reviews',
    ],
    metaTitle: 'Fitness Equipment Repair Cedar Hill TX | 2EZ TEK',
    metaDescription:
      'Fitness equipment repair in Cedar Hill, TX. Treadmill repair, home gym assembly, and commercial maintenance by 2EZ TEK.',
  },
]

export function getAreaBySlug(slug: string): AreaData | undefined {
  return areas.find((a) => a.slug === slug)
}

export function getAllAreaSlugs(): string[] {
  return areas.map((a) => a.slug)
}