// lib/brandData.ts

export interface BrandData {
  slug: string
  name: string
  tagline: string
  overview: string
  equipmentTypes: string[]
  commonIssues: string[]
  repairServices: string[]
  maintenancePrograms: string[]
  metaTitle: string
  metaDescription: string
}

export const brands: BrandData[] = [
  {
    slug: 'life-fitness',
    name: 'Life Fitness',
    tagline: 'Professional Life Fitness Equipment Repair in Dallas Fort Worth',
    overview:
      'Life Fitness is one of the most trusted names in commercial and residential fitness equipment. 2EZ TEK provides expert repair, preventative maintenance, and assembly services for the full Life Fitness lineup across Dallas Fort Worth — from treadmills and ellipticals to bikes, strength machines, and commercial cardio systems.',
    equipmentTypes: [
      'Life Fitness Treadmills',
      'Life Fitness Ellipticals',
      'Life Fitness Upright & Recumbent Bikes',
      'Life Fitness Cable & Strength Machines',
      'Life Fitness Discover SE3HD Consoles',
      'Life Fitness Commercial Cardio',
      'Life Fitness Platinum Club Series',
    ],
    commonIssues: [
      'Belt slipping or fraying on treadmills',
      'Console errors and touchscreen failures',
      'Incline motor failures',
      'Drive belt wear on ellipticals',
      'Resistance issues on bikes',
      'Cable and pulley wear on strength equipment',
      'Power board failures',
    ],
    repairServices: [
      'Treadmill belt replacement and lubrication',
      'Motor and drive system diagnostics',
      'Console repair and replacement',
      'Incline and elevation system repair',
      'Elliptical stride and resistance repair',
      'Strength machine cable and pulley service',
      'Full diagnostics and preventative tune-up',
    ],
    maintenancePrograms: [
      'Quarterly preventative maintenance visits',
      'Annual full-service inspection',
      'Commercial facility maintenance contracts',
      'Equipment asset tracking via SmartGymOps',
      'QR-based service reporting for facility managers',
    ],
    metaTitle: 'Life Fitness Repair Dallas Fort Worth | 2EZ TEK',
    metaDescription:
      'Expert Life Fitness equipment repair in Dallas Fort Worth. Treadmills, ellipticals, bikes, and strength machines serviced by certified technicians. Call 2EZ TEK.',
  },
  {
    slug: 'precor',
    name: 'Precor',
    tagline: 'Precor Equipment Repair and Maintenance in Dallas Fort Worth',
    overview:
      'Precor is renowned for its biomechanically engineered fitness equipment found in premium gyms, hotels, and corporate facilities. 2EZ TEK services the full Precor catalog across DFW, including their elliptical cross-trainers, treadmills, AMTs, and strength lines.',
    equipmentTypes: [
      'Precor Treadmills',
      'Precor Elliptical Cross-Trainers (EFX)',
      'Precor Adaptive Motion Trainers (AMT)',
      'Precor Upright & Recumbent Bikes',
      'Precor Strength & Functional Training',
      'Precor Discovery Series Selectorized',
      'Precor Commercial Cardio',
    ],
    commonIssues: [
      'EFX elliptical stride length issues',
      'AMT resistance and motion failures',
      'Treadmill deck and belt wear',
      'P80 console malfunctions',
      'Incline calibration errors',
      'Drive belt slipping or snapping',
      'Frame and weld stress on high-use equipment',
    ],
    repairServices: [
      'EFX and AMT drive system repair',
      'Treadmill belt and deck replacement',
      'Console diagnostics and firmware issues',
      'Incline motor and calibration service',
      'Resistance system repair on bikes',
      'Strength cable and selectorized stack service',
      'Full preventative tune-up and lubrication',
    ],
    maintenancePrograms: [
      'Scheduled preventative maintenance visits',
      'Commercial facility service contracts',
      'Equipment history tracking via SmartGymOps',
      'Priority response for facility managers',
      'Annual inspection and lubrication programs',
    ],
    metaTitle: 'Precor Repair Dallas Fort Worth | 2EZ TEK',
    metaDescription:
      'Professional Precor equipment repair in Dallas Fort Worth. EFX ellipticals, AMTs, treadmills, and strength equipment serviced by 2EZ TEK technicians.',
  },
  {
    slug: 'matrix',
    name: 'Matrix',
    tagline: 'Matrix Fitness Equipment Repair in Dallas Fort Worth',
    overview:
      'Matrix Fitness produces some of the most innovative commercial cardio and strength equipment on the market. 2EZ TEK provides repair, maintenance, and assembly services for the full Matrix lineup across Dallas Fort Worth — from their Endurance treadmills to functional trainers and selectorized strength systems.',
    equipmentTypes: [
      'Matrix Treadmills',
      'Matrix Ellipticals',
      'Matrix Upright & Recumbent Bikes',
      'Matrix Climbmill & Stairclimbers',
      'Matrix Functional Trainers',
      'Matrix Selectorized Strength',
      'Matrix Magnum Strength Series',
    ],
    commonIssues: [
      'Treadmill motor overheating',
      'Belt tracking and tension issues',
      'Console connectivity and touchscreen errors',
      'Resistance unit failures on bikes',
      'Functional trainer cable and pulley wear',
      'Climbmill step mechanism failures',
      'Drive belt wear on ellipticals',
    ],
    repairServices: [
      'Treadmill motor, belt, and deck service',
      'Console repair and software diagnostics',
      'Elliptical stride and resistance system repair',
      'Bike resistance and flywheel service',
      'Functional trainer cable and weight stack repair',
      'Climbmill step and drive system service',
      'Full equipment tune-up and lubrication',
    ],
    maintenancePrograms: [
      'Preventative maintenance for commercial facilities',
      'Equipment asset tracking via SmartGymOps',
      'Service history reporting for facility managers',
      'Annual inspection and lubrication visits',
      'Multi-unit maintenance contracts',
    ],
    metaTitle: 'Matrix Fitness Repair Dallas Fort Worth | 2EZ TEK',
    metaDescription:
      'Matrix fitness equipment repair in Dallas Fort Worth. Treadmills, ellipticals, functional trainers, and strength machines serviced by 2EZ TEK.',
  },
  {
    slug: 'technogym',
    name: 'Technogym',
    tagline: 'Technogym Equipment Repair and Service in Dallas Fort Worth',
    overview:
      'Technogym is the equipment of choice for elite facilities, luxury hotels, and professional sports organizations. 2EZ TEK provides expert Technogym repair and maintenance across Dallas Fort Worth — keeping your premium equipment performing at the level it was built for.',
    equipmentTypes: [
      'Technogym Treadmills',
      'Technogym Excite Cardio Line',
      'Technogym Skillmill & Skillbike',
      'Technogym Ellipticals',
      'Technogym Kinesis Functional Training',
      'Technogym Selectorized Strength',
      'Technogym ARTIS Series',
    ],
    commonIssues: [
      'UNITY console connectivity failures',
      'Skillmill belt and resistance issues',
      'Treadmill motor and drive belt wear',
      'Excite series resistance module failures',
      'Kinesis cable tension and pulley wear',
      'Software and firmware update errors',
      'Power supply and board failures',
    ],
    repairServices: [
      'Console and UNITY display diagnostics',
      'Treadmill motor, belt, and deck service',
      'Skillmill belt and resistance system repair',
      'Elliptical and cardio drive system repair',
      'Kinesis functional training cable service',
      'Strength machine cable and stack repair',
      'Full diagnostics and preventative tune-up',
    ],
    maintenancePrograms: [
      'Luxury facility maintenance contracts',
      'Priority response service agreements',
      'SmartGymOps-powered equipment tracking',
      'Quarterly and annual inspection programs',
      'Multi-location facility service coordination',
    ],
    metaTitle: 'Technogym Repair Dallas Fort Worth | 2EZ TEK',
    metaDescription:
      'Expert Technogym equipment repair in Dallas Fort Worth. ARTIS, Excite, Skillmill, and Kinesis serviced by 2EZ TEK technicians. Call today.',
  },
  {
    slug: 'cybex',
    name: 'Cybex',
    tagline: 'Cybex Fitness Equipment Repair in Dallas Fort Worth',
    overview:
      'Cybex builds high-performance cardio and strength equipment trusted by physical therapy clinics, commercial gyms, and athletic training facilities. 2EZ TEK services the full Cybex lineup across DFW with expert repair and maintenance.',
    equipmentTypes: [
      'Cybex Treadmills',
      'Cybex Arc Trainer',
      'Cybex Ellipticals',
      'Cybex Upright & Recumbent Bikes',
      'Cybex Eagle Strength Series',
      'Cybex VR3 Selectorized',
      'Cybex Bravo Functional Training',
    ],
    commonIssues: [
      'Arc Trainer resistance and stride issues',
      'Treadmill belt and motor failures',
      'Console error codes and display failures',
      'Eagle strength machine cable wear',
      'Resistance unit failures on bikes',
      'Drive belt and flywheel issues',
      'Frame and joint stress on high-use units',
    ],
    repairServices: [
      'Arc Trainer drive and resistance system repair',
      'Treadmill belt, deck, and motor service',
      'Console diagnostics and replacement',
      'Eagle strength cable and stack service',
      'Bike resistance and flywheel repair',
      'Full equipment diagnostics and tune-up',
      'Bravo functional trainer cable service',
    ],
    maintenancePrograms: [
      'Preventative maintenance for commercial and clinical facilities',
      'Scheduled inspection and lubrication programs',
      'SmartGymOps equipment tracking',
      'Service history and QR reporting',
      'Multi-unit maintenance contracts',
    ],
    metaTitle: 'Cybex Equipment Repair Dallas Fort Worth | 2EZ TEK',
    metaDescription:
      'Cybex fitness equipment repair in Dallas Fort Worth. Arc Trainers, treadmills, Eagle strength, and more serviced by 2EZ TEK. Book service today.',
  },
  {
    slug: 'stairmaster',
    name: 'StairMaster',
    tagline: 'StairMaster Repair and Maintenance in Dallas Fort Worth',
    overview:
      'StairMaster is the gold standard in stair climbing and step mill cardio equipment. 2EZ TEK provides expert repair and preventative maintenance for StairMaster equipment across Dallas Fort Worth, from the legendary 7000PT to the Gauntlet and 10G step mills.',
    equipmentTypes: [
      'StairMaster Gauntlet StepMill',
      'StairMaster 10G StepMill',
      'StairMaster 8 Series',
      'StairMaster HIIT Bike',
      'StairMaster Freeclimber',
      'StairMaster Steppers',
      'StairMaster Commercial Cardio',
    ],
    commonIssues: [
      'Step belt slipping or jamming',
      'Drive chain and sprocket wear',
      'Console and display malfunctions',
      'Resistance system failures',
      'Motor overheating on high-use units',
      'Pedal and step pad wear',
      'Power supply issues',
    ],
    repairServices: [
      'Step belt replacement and tensioning',
      'Drive chain and sprocket service',
      'Motor diagnostics and replacement',
      'Console and display repair',
      'Resistance system diagnostics',
      'Full preventative maintenance and lubrication',
      'Emergency repair for commercial facilities',
    ],
    maintenancePrograms: [
      'Quarterly step belt and chain inspections',
      'Commercial facility maintenance contracts',
      'SmartGymOps equipment tracking and reporting',
      'Annual full-service inspections',
      'Priority response for high-use facilities',
    ],
    metaTitle: 'StairMaster Repair Dallas Fort Worth | 2EZ TEK',
    metaDescription:
      'StairMaster repair and maintenance in Dallas Fort Worth. Gauntlet, 10G, and StepMill service by 2EZ TEK technicians. Book your repair today.',
  },
  {
    slug: 'nordictrack',
    name: 'NordicTrack',
    tagline: 'NordicTrack Equipment Repair in Dallas Fort Worth',
    overview:
      'NordicTrack is one of the most popular home fitness brands in America. 2EZ TEK provides professional NordicTrack repair and assembly services across Dallas Fort Worth — from treadmill belt replacements to iFit console repairs and elliptical tune-ups.',
    equipmentTypes: [
      'NordicTrack Treadmills',
      'NordicTrack Ellipticals',
      'NordicTrack Bikes (S22i, Commercial)',
      'NordicTrack Rowers',
      'NordicTrack Fusion CST',
      'NordicTrack iFit-Enabled Equipment',
      'NordicTrack Incline Trainers',
    ],
    commonIssues: [
      'Treadmill belt slipping or fraying',
      'iFit console connectivity issues',
      'Incline motor failures',
      'Elliptical squeaking and resistance issues',
      'S22i bike resistance and screen failures',
      'Folding mechanism failures',
      'Motor board and controller errors',
    ],
    repairServices: [
      'Treadmill belt and deck replacement',
      'Motor and controller diagnostics',
      'iFit console and screen repair',
      'Incline motor repair and calibration',
      'Elliptical drive and resistance service',
      'Bike resistance unit and flywheel repair',
      'Assembly and installation services',
    ],
    maintenancePrograms: [
      'Home gym preventative maintenance visits',
      'Annual tune-up and lubrication programs',
      'Assembly and relocation services',
      'SmartGymOps service history tracking',
      'Multi-unit residential maintenance',
    ],
    metaTitle: 'NordicTrack Repair Dallas Fort Worth | 2EZ TEK',
    metaDescription:
      'NordicTrack treadmill, elliptical, and bike repair in Dallas Fort Worth. iFit console and incline motor specialists. Call 2EZ TEK today.',
  },
  {
    slug: 'bowflex',
    name: 'Bowflex',
    tagline: 'Bowflex Equipment Repair and Assembly in Dallas Fort Worth',
    overview:
      'Bowflex produces a wide range of home gym equipment from treadmills and bikes to cable systems and free weights. 2EZ TEK provides expert Bowflex repair, assembly, and maintenance services across Dallas Fort Worth.',
    equipmentTypes: [
      'Bowflex Treadmills',
      'Bowflex Max Trainer',
      'Bowflex VeloCore Bike',
      'Bowflex Ellipticals',
      'Bowflex Home Gym Cable Systems',
      'Bowflex SelectTech Equipment',
      'Bowflex Xtreme & Blaze Systems',
    ],
    commonIssues: [
      'Max Trainer resistance and motion failures',
      'Treadmill belt wear and motor issues',
      'VeloCore bike lean mechanism failures',
      'Cable tension and resistance rod wear',
      'Console and display errors',
      'Assembly issues on newly delivered units',
      'Squeaking and structural noise',
    ],
    repairServices: [
      'Max Trainer resistance and drive repair',
      'Treadmill belt, deck, and motor service',
      'VeloCore lean mechanism and resistance repair',
      'Cable system tension and pulley service',
      'Console diagnostics and replacement',
      'Full assembly and installation',
      'Structural repair and noise diagnosis',
    ],
    maintenancePrograms: [
      'Home gym preventative maintenance',
      'Annual inspection and lubrication',
      'Assembly and white-glove installation',
      'Relocation and reinstallation services',
      'SmartGymOps service history tracking',
    ],
    metaTitle: 'Bowflex Repair Dallas Fort Worth | 2EZ TEK',
    metaDescription:
      'Bowflex repair and assembly in Dallas Fort Worth. Max Trainer, VeloCore, treadmills, and home gym systems serviced by 2EZ TEK. Book today.',
  },
  {
    slug: 'true-fitness',
    name: 'TRUE Fitness',
    tagline: 'TRUE Fitness Equipment Repair in Dallas Fort Worth',
    overview:
      'TRUE Fitness is known for building some of the most durable and orthopedically sound fitness equipment available. 2EZ TEK services the full TRUE Fitness lineup across Dallas Fort Worth including their treadmills, ellipticals, and bikes.',
    equipmentTypes: [
      'TRUE Treadmills',
      'TRUE Ellipticals',
      'TRUE Upright & Recumbent Bikes',
      'TRUE Traverse Trainer',
      'TRUE Commercial Cardio',
      'TRUE PS800 & PS900 Treadmills',
      'TRUE Alpine Runner',
    ],
    commonIssues: [
      'Treadmill belt and deck wear',
      'Drive belt slipping or snapping',
      'Orthopedic deck cushioning failures',
      'Console display malfunctions',
      'Elliptical resistance and drive issues',
      'Incline motor failures',
      'Motor controller board errors',
    ],
    repairServices: [
      'Treadmill belt, deck, and motor repair',
      'Drive belt and roller replacement',
      'Orthopedic deck replacement',
      'Console and display diagnostics',
      'Elliptical stride and resistance repair',
      'Incline motor service and calibration',
      'Full preventative maintenance and tune-up',
    ],
    maintenancePrograms: [
      'Commercial facility maintenance contracts',
      'Annual inspection and lubrication visits',
      'SmartGymOps equipment tracking',
      'Scheduled preventative maintenance programs',
      'Priority response for high-use facilities',
    ],
    metaTitle: 'TRUE Fitness Repair Dallas Fort Worth | 2EZ TEK',
    metaDescription:
      'TRUE Fitness equipment repair in Dallas Fort Worth. Treadmills, ellipticals, and bikes serviced by 2EZ TEK technicians. Call today.',
  },
  {
    slug: 'schwinn',
    name: 'Schwinn',
    tagline: 'Schwinn Bike and Fitness Equipment Repair in Dallas Fort Worth',
    overview:
      'Schwinn is one of the most recognized names in cycling and fitness. 2EZ TEK services Schwinn bikes, indoor cycles, and cardio equipment across Dallas Fort Worth for both residential and light commercial clients.',
    equipmentTypes: [
      'Schwinn Indoor Cycling Bikes',
      'Schwinn Upright & Recumbent Bikes',
      'Schwinn Airdyne Bikes',
      'Schwinn Ellipticals',
      'Schwinn Treadmills',
      'Schwinn 230 & 270 Recumbent',
      'Schwinn IC4 & AC Performance Series',
    ],
    commonIssues: [
      'Resistance system failures on indoor cycles',
      'Airdyne belt and fan drive issues',
      'Console and display malfunctions',
      'Pedal and crank arm wear',
      'Flywheel resistance and magnetic system issues',
      'Seat and handlebar adjustment failures',
      'Drive belt wear on upright bikes',
    ],
    repairServices: [
      'Indoor cycle resistance and magnetic system repair',
      'Airdyne belt and drive service',
      'Console diagnostics and replacement',
      'Pedal, crank, and flywheel service',
      'Upright and recumbent drive system repair',
      'Full bike tune-up and lubrication',
      'Assembly and installation services',
    ],
    maintenancePrograms: [
      'Home gym and studio bike maintenance',
      'Annual tune-up and lubrication programs',
      'Assembly and installation services',
      'SmartGymOps service tracking',
      'Scheduled preventative maintenance visits',
    ],
    metaTitle: 'Schwinn Bike Repair Dallas Fort Worth | 2EZ TEK',
    metaDescription:
      'Schwinn bike and fitness equipment repair in Dallas Fort Worth. Indoor cycles, Airdyne, and recumbent bikes serviced by 2EZ TEK.',
  },
  {
    slug: 'nautilus',
    name: 'Nautilus',
    tagline: 'Nautilus Equipment Repair and Service in Dallas Fort Worth',
    overview:
      'Nautilus builds quality home and light commercial fitness equipment including treadmills, bikes, and ellipticals. 2EZ TEK provides expert Nautilus repair and assembly services across Dallas Fort Worth.',
    equipmentTypes: [
      'Nautilus Treadmills',
      'Nautilus Upright & Recumbent Bikes',
      'Nautilus Ellipticals',
      'Nautilus T616 & T618 Treadmills',
      'Nautilus E614 & E618 Ellipticals',
      'Nautilus R616 Recumbent Bike',
      'Nautilus Home Gym Equipment',
    ],
    commonIssues: [
      'Treadmill motor and belt failures',
      'Console connectivity and display errors',
      'Elliptical resistance and flywheel issues',
      'Bike resistance system failures',
      'Incline motor errors',
      'Folding hinge and locking mechanism failures',
      'Drive belt wear',
    ],
    repairServices: [
      'Treadmill belt, deck, and motor repair',
      'Console diagnostics and replacement',
      'Elliptical resistance and drive service',
      'Bike flywheel and resistance repair',
      'Incline motor service',
      'Full assembly and installation',
      'Preventative tune-up and lubrication',
    ],
    maintenancePrograms: [
      'Home gym preventative maintenance visits',
      'Annual inspection and lubrication',
      'Assembly and relocation services',
      'SmartGymOps service history tracking',
      'Scheduled maintenance programs',
    ],
    metaTitle: 'Nautilus Equipment Repair Dallas Fort Worth | 2EZ TEK',
    metaDescription:
      'Nautilus treadmill, bike, and elliptical repair in Dallas Fort Worth. Expert service by 2EZ TEK technicians. Book your repair today.',
  },
  {
    slug: 'octane-fitness',
    name: 'Octane Fitness',
    tagline: 'Octane Fitness Equipment Repair in Dallas Fort Worth',
    overview:
      'Octane Fitness is known for their zero-impact lateral ellipticals, seated ellipticals, and innovative cardio designs. 2EZ TEK services Octane Fitness equipment across Dallas Fort Worth for commercial and residential clients.',
    equipmentTypes: [
      'Octane Q47 & Q37 Ellipticals',
      'Octane LateralX Elliptical',
      'Octane Zero Runner',
      'Octane XT One Elliptical',
      'Octane Seated Ellipticals',
      'Octane Airdyne & Commercial Cardio',
      'Octane CROSS CiRCUIT',
    ],
    commonIssues: [
      'LateralX lateral motion resistance failures',
      'Zero Runner stride pad and drive issues',
      'Elliptical resistance unit failures',
      'Console and touchscreen errors',
      'Drive belt and flywheel wear',
      'Pedal and stride arm joint wear',
      'Motor controller errors',
    ],
    repairServices: [
      'LateralX resistance and motion system repair',
      'Zero Runner stride and drive service',
      'Elliptical resistance unit replacement',
      'Console diagnostics and display repair',
      'Drive belt and flywheel service',
      'Pedal and joint wear repair',
      'Full equipment tune-up and lubrication',
    ],
    maintenancePrograms: [
      'Commercial and studio maintenance contracts',
      'Scheduled preventative maintenance visits',
      'SmartGymOps equipment tracking',
      'Annual inspection programs',
      'Priority response for facility managers',
    ],
    metaTitle: 'Octane Fitness Repair Dallas Fort Worth | 2EZ TEK',
    metaDescription:
      'Octane Fitness equipment repair in Dallas Fort Worth. LateralX, Zero Runner, and elliptical service by 2EZ TEK. Book today.',
  },
  {
    slug: 'star-trac',
    name: 'Star Trac',
    tagline: 'Star Trac Equipment Repair and Maintenance in Dallas Fort Worth',
    overview:
      'Star Trac is a trusted commercial fitness brand found in hotels, gyms, and corporate fitness centers worldwide. 2EZ TEK provides expert Star Trac repair and preventative maintenance across Dallas Fort Worth.',
    equipmentTypes: [
      'Star Trac Treadmills',
      'Star Trac Ellipticals',
      'Star Trac Upright & Recumbent Bikes',
      'Star Trac Spinning Bikes',
      'Star Trac E-Series Cardio',
      'Star Trac S-Series Cardio',
      'Star Trac Commercial Equipment',
    ],
    commonIssues: [
      'Treadmill belt and deck wear',
      'Motor and drive belt failures',
      'Console and touchscreen malfunctions',
      'Elliptical resistance and drive issues',
      'Spinning bike flywheel and resistance failures',
      'Incline motor errors',
      'Power supply and board failures',
    ],
    repairServices: [
      'Treadmill belt, deck, and motor service',
      'Drive belt replacement and tensioning',
      'Console and display diagnostics',
      'Elliptical resistance and drive repair',
      'Spinning bike resistance and flywheel service',
      'Full equipment diagnostics and tune-up',
      'Commercial facility emergency repair',
    ],
    maintenancePrograms: [
      'Commercial facility maintenance contracts',
      'Quarterly and annual inspection programs',
      'SmartGymOps equipment tracking',
      'Service history reporting for facility managers',
      'Multi-unit maintenance agreements',
    ],
    metaTitle: 'Star Trac Repair Dallas Fort Worth | 2EZ TEK',
    metaDescription:
      'Star Trac fitness equipment repair in Dallas Fort Worth. Treadmills, ellipticals, and commercial cardio serviced by 2EZ TEK technicians.',
  },
  {
    slug: 'freemotion',
    name: 'FreeMotion',
    tagline: 'FreeMotion Equipment Repair and Service in Dallas Fort Worth',
    overview:
      'FreeMotion is known for its innovative cable-based strength training systems and commercial fitness equipment. 2EZ TEK services FreeMotion equipment across Dallas Fort Worth, from their iconic dual cable machines to treadmills and ellipticals.',
    equipmentTypes: [
      'FreeMotion Dual Cable Cross',
      'FreeMotion Functional Trainers',
      'FreeMotion Treadmills',
      'FreeMotion Ellipticals',
      'FreeMotion Incline Trainers',
      'FreeMotion EXT Elliptical',
      'FreeMotion Commercial Strength',
    ],
    commonIssues: [
      'Cable and pulley system wear',
      'Weight stack and selectorized failures',
      'Treadmill belt and motor issues',
      'Incline trainer motor and belt failures',
      'Console and touchscreen errors',
      'Elliptical drive and resistance issues',
      'Cable tension imbalance',
    ],
    repairServices: [
      'Dual cable and pulley system repair',
      'Weight stack and selector pin service',
      'Treadmill belt, deck, and motor repair',
      'Incline trainer drive and motor service',
      'Console and display diagnostics',
      'Elliptical resistance and drive repair',
      'Full functional trainer cable replacement',
    ],
    maintenancePrograms: [
      'Commercial gym cable system maintenance',
      'Quarterly and annual inspection programs',
      'SmartGymOps equipment asset tracking',
      'Preventative maintenance contracts',
      'Service history reporting for facility managers',
    ],
    metaTitle: 'FreeMotion Repair Dallas Fort Worth | 2EZ TEK',
    metaDescription:
      'FreeMotion fitness equipment repair in Dallas Fort Worth. Cable machines, functional trainers, treadmills, and ellipticals serviced by 2EZ TEK.',
  },
  {
    slug: 'hammer-strength',
    name: 'Hammer Strength',
    tagline: 'Hammer Strength Equipment Repair in Dallas Fort Worth',
    overview:
      'Hammer Strength by Life Fitness is the premier brand for plate-loaded and selectorized strength equipment. Trusted by professional sports teams and elite training facilities, Hammer Strength requires expert service. 2EZ TEK provides dedicated Hammer Strength repair and maintenance across Dallas Fort Worth.',
    equipmentTypes: [
      'Hammer Strength Plate-Loaded Equipment',
      'Hammer Strength MTS Selectorized',
      'Hammer Strength HD Elite Series',
      'Hammer Strength Iso-Lateral Machines',
      'Hammer Strength Ground Base Equipment',
      'Hammer Strength Athletic Benches & Racks',
      'Hammer Strength Commercial Strength Systems',
    ],
    commonIssues: [
      'Selectorized cable and pulley wear',
      'Upholstery and pad deterioration',
      'Weight stack and pin failures',
      'Roller and pivot bearing wear',
      'Frame weld stress on high-use machines',
      'Cable fraying and tension loss',
      'Seat and adjustment mechanism failures',
    ],
    repairServices: [
      'Cable and pulley system replacement',
      'Weight stack and selector pin service',
      'Upholstery and pad replacement',
      'Roller, pivot, and bearing service',
      'Frame inspection and structural repair',
      'Full equipment diagnostics and tune-up',
      'Commercial strength room maintenance',
    ],
    maintenancePrograms: [
      'Commercial and athletic facility maintenance contracts',
      'Quarterly inspection and lubrication programs',
      'SmartGymOps equipment tracking and reporting',
      'Annual full-service inspection visits',
      'Multi-unit strength room maintenance agreements',
    ],
    metaTitle: 'Hammer Strength Repair Dallas Fort Worth | 2EZ TEK',
    metaDescription:
      'Hammer Strength equipment repair in Dallas Fort Worth. Plate-loaded, MTS selectorized, and HD Elite strength systems serviced by 2EZ TEK.',
  },
  {
    slug: 'sportsart',
    name: 'SportsArt',
    tagline: 'SportsArt Fitness Equipment Repair in Dallas Fort Worth',
    overview:
      'SportsArt is an innovative fitness equipment brand known for their energy-generating ECO-POWR line and commercial cardio equipment. 2EZ TEK provides expert SportsArt repair and maintenance services across Dallas Fort Worth.',
    equipmentTypes: [
      'SportsArt ECO-POWR Treadmills',
      'SportsArt ECO-POWR Bikes',
      'SportsArt Ellipticals',
      'SportsArt Status Series Cardio',
      'SportsArt Selectorized Strength',
      'SportsArt Cable & Functional Training',
      'SportsArt Commercial Cardio',
    ],
    commonIssues: [
      'ECO-POWR energy generation system failures',
      'Treadmill motor and belt wear',
      'Console and touchscreen malfunctions',
      'Elliptical resistance and drive issues',
      'Bike resistance and flywheel failures',
      'Cable and pulley wear on strength equipment',
      'Power board and controller errors',
    ],
    repairServices: [
      'ECO-POWR system diagnostics and repair',
      'Treadmill belt, deck, and motor service',
      'Console and display repair',
      'Elliptical resistance and drive system repair',
      'Bike resistance and flywheel service',
      'Strength cable and pulley replacement',
      'Full equipment diagnostics and tune-up',
    ],
    maintenancePrograms: [
      'Commercial facility maintenance contracts',
      'Annual inspection and lubrication programs',
      'SmartGymOps equipment tracking',
      'Scheduled preventative maintenance visits',
      'Priority response for facility managers',
    ],
    metaTitle: 'SportsArt Repair Dallas Fort Worth | 2EZ TEK',
    metaDescription:
      'SportsArt fitness equipment repair in Dallas Fort Worth. ECO-POWR, cardio, and strength equipment serviced by 2EZ TEK technicians. Call today.',
  },
]

export function getBrandBySlug(slug: string): BrandData | undefined {
  return brands.find((b) => b.slug === slug)
}

export function getAllBrandSlugs(): string[] {
  return brands.map((b) => b.slug)
}