export type ThumbtackReview = {
  name: string
  title: string
  review: string
  service: string
  date: string
}

export const thumbtackReviews: ThumbtackReview[] = [
  {
    name: 'Jordan C.',
    title: 'Prompt and knowledgeable on Smith machine',
    review: 'Prompt, professional and knowledgeable on assembling our smith machine. We are very happy with the service we received and would use again!',
    service: 'Fitness Equipment Assembly',
    date: 'Mar 2026',
  },
  {
    name: 'Ron W.',
    title: 'Responsive, reasonable and professional',
    review: 'Responsive, reasonable and professional',
    service: 'Fitness Equipment Assembly',
    date: 'Feb 2026',
  },
  {
    name: 'Jessie C.',
    title: 'Quick response, job done as requested',
    review: 'Quick response and got the job done as requested.',
    service: 'Fitness Equipment Assembly',
    date: 'Feb 2026',
  },
  {
    name: 'Josh G.',
    title: 'Answered when others would not',
    review: 'We could not be more pleased with the great work and experience we had working with Robbie. My wife was up in arms about her broken treadmill. After reaching out to several repair options with no answer, Robbie answered the call and was timely, affordable, and really easy to work with. 5 stars!',
    service: 'Exercise Equipment Repair',
    date: 'Dec 2025',
  },
  {
    name: 'Rex K.',
    title: 'Great experience',
    review: 'Great experience',
    service: 'Fitness Equipment Assembly',
    date: 'Nov 2025',
  },
  {
    name: 'Holly L.',
    title: 'Would absolutely use 2EZ TEK again',
    review: 'I would absolutely use 2EZ TEK again! They were prompt, very professional, and knew exactly what the issue was. They quickly assembled and fixed everything perfectly. I wish all service providers were this efficient and easy to work with. Thank you, 2EZ TEK!',
    service: 'Exercise Equipment Repair',
    date: 'Nov 2025',
  },
  {
    name: 'David S.',
    title: 'Belt replaced, runs better than ever',
    review: 'Replaced treadmill belt and tuned up. Ran on it this evening and everything is working well. Very thorough and considerate.',
    service: 'Exercise Equipment Repair',
    date: 'Nov 2025',
  },
  {
    name: 'Jasmin',
    title: 'Fast, knowledgeable, will use again',
    review: 'He worked fast and great work was already knowledgeable on the equipment I will definitely use again',
    service: 'Fitness Equipment Assembly',
    date: 'Nov 2025',
  },
  {
    name: 'Hope J.',
    title: 'Friendly and completed the job perfectly',
    review: 'Very friendly and helpful. He knew what he was doing and completed the assembly of my home gym machine.',
    service: 'Fitness Equipment Assembly',
    date: 'Oct 2025',
  },
  {
    name: 'Miguel E.',
    title: 'Solo job done under 2 hours',
    review: "Knocked it out solo in under 2hrs. All works well I'm impressed. Will be doing further business with this gentleman thank you sir.",
    service: 'Fitness Equipment Assembly',
    date: 'Oct 2025',
  },
  {
    name: 'Stephanie A.',
    title: 'On time and explained every step',
    review: 'Robbie was quick to respond to schedule an appointment. He showed up on time and took time to explain what was wrong and the steps he took to find a resolution.',
    service: 'Exercise Equipment Repair',
    date: 'Oct 2025',
  },
  {
    name: 'Erin C.',
    title: 'Fixed in 5 minutes where 2 others failed',
    review: "There a reason he has so many 5 star reviews! Had 2 techs come out before and didn't know how to fix our treadmill. He fixed it within 5 minutes. Best of the best!",
    service: 'Exercise Equipment Repair',
    date: 'Sep 2025',
  },
  {
    name: 'Verified Customer',
    title: 'Knowledgeable on Sunny exercise bikes',
    review: 'Robbie was very knowledgeable about Sunny exercise bike. Gave me info needed to order replacement console from Sunny after he decided that was most likely the problem.',
    service: 'Exercise Equipment Repair',
    date: 'Sep 2025',
  },
  {
    name: 'Tommy L.',
    title: 'Treadmill running again in minutes',
    review: 'Robbie quickly diagnosed the problem and within a few minutes had my treadmill up and running again. I highly recommend his service.',
    service: 'Exercise Equipment Repair',
    date: 'Sep 2025',
  },
  {
    name: 'Verified Customer',
    title: 'Great expertise',
    review: 'Great expertise',
    service: 'Exercise Equipment Repair',
    date: 'Sep 2025',
  },
  {
    name: 'Courtney N.',
    title: 'Excellent service',
    review: 'Excellent service!',
    service: 'Exercise Equipment Repair',
    date: 'Sep 2025',
  },
  {
    name: 'Robert',
    title: 'Very pleased, added them to my contacts',
    review: 'Great Service first time using Very pleased. Added Company to my contact list.',
    service: 'Fitness Equipment Assembly',
    date: 'Sep 2025',
  },
  {
    name: 'Mohamed',
    title: 'Fixed 3 machines in a single visit',
    review: "Roby was fantastic, very professional I had 3 items to fix in a day a large heavy functional trainer a treadmill and a huge trampoline he's highly skilled and fixed it all the same day and was very courteous and easy to talk to decent with pricing aswell 100% will hire again and highly recommend!!!",
    service: 'Fitness Equipment Assembly',
    date: 'Aug 2025',
  },
  {
    name: 'Deb R.',
    title: 'Explained everything, resolved in minutes',
    review: 'Rob explained the situation thoroughly and had it resolved within minutes',
    service: 'Exercise Equipment Repair',
    date: 'Aug 2025',
  },
  {
    name: 'Rebecca J.',
    title: 'Even assembled a treadmill for our dog',
    review: 'My request was a little unusual, assemble a treadmill specifically for a dog! 2ez tek was incredibly responsive, excellent with communication and scheduling and completed the project quickly and exactly to specs. Very happy with result. So are the pups',
    service: 'Fitness Equipment Assembly',
    date: 'Aug 2025',
  },
  {
    name: 'Lesley T.',
    title: 'Knew exactly what to do, no guessing',
    review: "I was amazed and impressed with how quickly Robby got my elliptical machine fixed. Other pros were telling me that they were gonna have to take the time to figure out what the problem was, and I got the impression that they were having to guess on how to fix the problem, but Robby knew what to do right away. He is certified and very qualified.",
    service: 'Exercise Equipment Repair',
    date: 'Aug 2025',
  },
  {
    name: 'Kevin C.',
    title: 'Second time hiring, would not hesitate again',
    review: "This was my second time working with 2EZ TEK LLC. I would recommend them to anyone looking to build a home gym or simply just putting gym equipment together! Awesome job and wouldn't hesitate to hire them again.",
    service: 'Exercise Equipment Repair',
    date: 'Jul 2025',
  },
  {
    name: 'Verified Customer',
    title: 'Knowledgeable and helpful with assembly',
    review: 'Rob is too knowledgable and helped us in assembling the equipment',
    service: 'Fitness Equipment Assembly',
    date: 'Jul 2025',
  },
  {
    name: 'Krisanne H.',
    title: 'Quick assembly at a great price',
    review: 'The assembly was quick. I appreciate the timeliness and the price! Thank You!!',
    service: 'Fitness Equipment Assembly',
    date: 'Jul 2025',
  },
  {
    name: 'Lon B.',
    title: 'Thorough professionals in their field',
    review: 'This company was quick to respond, adept in diagnosing and thorough with repair and recommendations. Truly professionals in their field. I would use them again in a heartbeat.',
    service: 'Exercise Equipment Repair',
    date: 'Jul 2025',
  },
  {
    name: 'Verified Customer',
    title: 'Identified the problem, cost-effective fix',
    review: 'Robby helped fix my broken treadmill. He quickly identified the problem and gave me a cost effective solution.',
    service: 'Exercise Equipment Repair',
    date: 'Jul 2025',
  },
  {
    name: 'Melissa A.',
    title: 'Exceptional across the board',
    review: 'Exceptional communication, professionalism, and responsiveness. We will definitely use this service again, fixed the issue timely and accurately, very knowledgeable. Thank you so much!',
    service: 'Exercise Equipment Repair',
    date: 'Jun 2025',
  },
  {
    name: 'Kevin G.',
    title: 'A+ grade, recommended without hesitation',
    review: "First off I need to give Robby the dues he rightfully deserves with a resounding grade of A+. He no doubt knows exactly what he's doing & I'm Very grateful I went with this company. I would recommend this LLC to everyone without hesitation. Thanks Robby, Kevin",
    service: 'Fitness Equipment Assembly',
    date: 'May 2025',
  },
  {
    name: 'Rolanda J.',
    title: 'Up and running in no time',
    review: "Orlando was great! He came in, got to work, and had my treadmill up in no time at all. I'm an avid runner so really happy to have gotten this alternative set up for bad weather days! Thank you, Orlando!",
    service: 'Fitness Equipment Assembly',
    date: 'May 2025',
  },
  {
    name: 'Kyra D.',
    title: 'Same day setup, amazing response time',
    review: 'Amazing response time. Equipment was delivered super early and he was able to come out and get it setup same day!!! Huge thanks',
    service: 'Fitness Equipment Assembly',
    date: 'Apr 2025',
  },
  {
    name: 'Krishna S.',
    title: 'Professional, knew his job very well',
    review: "I liked Robby's professionalism. He knew his job very well.",
    service: 'Exercise Equipment Repair',
    date: 'Apr 2025',
  },
  {
    name: 'Chelsea C.',
    title: 'Part on hand, in and out in 30 minutes',
    review: 'Very impressed by the professionalism! Very prompt and worked quickly. He had the part on hand so he was in and out in only 30 minutes. The process was seamless and I will definitely use him moving forward.',
    service: 'Exercise Equipment Repair',
    date: 'Apr 2025',
  },
  {
    name: 'Laura L.',
    title: 'Came on a weekend, everything works great',
    review: 'Came on a weekend. Was super polite and knowledgeable. My spin bike works great, along with my treadclimber. Would hire again.',
    service: 'Exercise Equipment Repair',
    date: 'Apr 2025',
  },
  {
    name: 'Conrad P.',
    title: 'Great to work with on treadmill install',
    review: 'They were great to work with installing our treadmill.',
    service: 'Fitness Equipment Assembly',
    date: 'Apr 2025',
  },
  {
    name: 'Ron P.',
    title: 'Terrific, solved our problem',
    review: 'Robbie was terrific, solved our problem, thanks again',
    service: 'Exercise Equipment Repair',
    date: 'Apr 2025',
  },
  {
    name: 'Tony',
    title: 'Very good service',
    review: 'Very good',
    service: 'Exercise Equipment Repair',
    date: 'Apr 2025',
  },
  {
    name: 'Eric E.',
    title: 'Timely response and a quick fix',
    review: 'Timely response and a quick fix. All good.',
    service: 'Exercise Equipment Repair',
    date: 'Apr 2025',
  },
  {
    name: 'Justin M.',
    title: 'Came back to fix a small item, no charge',
    review: "Robby was incredibly professional and did a great job installing my rogue functional trainer. It was a massive project that Robby did quickly and efficiently, and he even came back out to fix a small item I noticed several days later. I would highly recommend Robby's services to anyone looking to have their gym equipment installed and put together. It saved me hours (maybe even days) of time letting the professional do it.",
    service: 'Fitness Equipment Assembly',
    date: 'Apr 2025',
  },
  {
    name: 'Kaylyn R.',
    title: 'Quick, efficient, total peace of mind',
    review: "I am so happy to have found this business and will be definitely using them in the future as I add to my gym! He was quick, efficient, and I had peace of mind in trusting him in doing something I hadn't been able to find with other companies. Use them, you won't regret it!!",
    service: 'Fitness Equipment Assembly',
    date: 'Apr 2025',
  },
  {
    name: 'Joshua J.',
    title: 'Everything assembled perfectly and quickly',
    review: "Truly a great service! We love our Ritfit M1 2.0. Everything was assembled perfectly & in a timely manner (Quickly). Don't hesitate!",
    service: 'Fitness Equipment Assembly',
    date: 'Mar 2025',
  },
  {
    name: 'Andrew M.',
    title: 'Quick, professional and reasonably priced',
    review: 'Quick, professional and reasonably priced.',
    service: 'Exercise Equipment Repair',
    date: 'Mar 2025',
  },
  {
    name: 'Sean N.',
    title: 'Extremely satisfied',
    review: 'Extremely satisfied',
    service: 'Fitness Equipment Assembly',
    date: 'Mar 2025',
  },
  {
    name: 'Penny H.',
    title: 'Quick and explained what he did',
    review: 'Robby was great, quick and explained what he did and what to watch for. Thank you',
    service: 'Exercise Equipment Repair',
    date: 'Feb 2025',
  },
  {
    name: 'Rose C.',
    title: 'Fixed treadmill incline issue',
    review: 'Great Experience! Thank you Rob for fixing our treadmill incline issue!!!',
    service: 'Exercise Equipment Repair',
    date: 'Feb 2025',
  },
  {
    name: 'Heather M.',
    title: 'Familiar with the brand, works great',
    review: 'Thank you Robby for the disassembly/reassembly of our treadmill. Your familiarity with the brand was a real comfort and the tread works great!',
    service: 'Fitness Equipment Assembly',
    date: 'Feb 2025',
  },
  {
    name: 'Raja M.',
    title: 'On time and completed as promised',
    review: 'He arrived on time and completed the work as promised.',
    service: 'Fitness Equipment Assembly',
    date: 'Feb 2025',
  },
  {
    name: 'Jose R.',
    title: 'Amazing service and very punctual',
    review: 'Amazing service and very punctual',
    service: 'Exercise Equipment Repair',
    date: 'Feb 2025',
  },
  {
    name: 'Shannon L.',
    title: 'Punctual, quick and informative',
    review: 'Robby was great to work with! He was punctual, quick, and gave me the information I needed to register my treadmill. Other companies I was in contact with were not reliable with their time and I am so glad I ultimately decided to go with this company!',
    service: 'Fitness Equipment Assembly',
    date: 'Feb 2025',
  },
  {
    name: 'Pamela H.',
    title: 'Will be my go-to for treadmill repairs',
    review: 'Robby was punctual, responsive, and very professional. He will be my go-to guy for any other treadmill repairs.',
    service: 'Exercise Equipment Repair',
    date: 'Jan 2025',
  },
  {
    name: 'David G.',
    title: 'Same day service on a Sunday',
    review: 'Great experience with rob! Came out same day (Sunday) to align treadmill belt! Was knowledgeable and explained all questions asked in a professional manner! Thanks rob',
    service: 'Exercise Equipment Repair',
    date: 'Jan 2025',
  },
  {
    name: 'Rupesh S.',
    title: 'Faster than expected, cleaned up after',
    review: 'Professional and efficient. Finished the job faster than expected and cleaned up after himself. Will use for future projects.',
    service: 'Exercise Equipment Repair',
    date: 'Jan 2025',
  },
  {
    name: 'Marcus M.',
    title: 'Less than 24 hours notice, still perfect',
    review: 'Awesome person who provided excellent work. Did the job for me with less than 24hrs notice. He was very punctual and did an awesome job! Would highly recommend for any handyman jobs you may need done!',
    service: 'Fitness Equipment Assembly',
    date: 'Jan 2025',
  },
  {
    name: 'Ivan D.',
    title: 'Found extra issues and fixed them too',
    review: "Rob was amazing gave me options over the phone then realized when he came that it was just a calibration issue. He even noticed the belt wasn't aligned and fixed it. Would recommend him to all for any of your fitness equipment needs",
    service: 'Exercise Equipment Repair',
    date: 'Dec 2024',
  },
  {
    name: 'Rasheeda G.',
    title: 'Flawless Rogue Fitness trainer assembly',
    review: "I can't thank 2EZ TEK enough for their incredible work assembling my Rogue Fitness RM-6 Functional Trainer! From start to finish, they were professional, efficient, and clearly experienced with this type of equipment. The RM-6 Functional Trainer is no small task to put together, but they made it look easy. Every bolt was tightened perfectly, and the machine was assembled flawlessly completely level and stable. They even took the time to walk me through the setup, ensuring I knew how to adjust the pulleys and attachments properly. Their attention to detail and commitment to doing the job right gave me complete confidence in the safety and functionality of the trainer. If you're investing in high-quality fitness equipment, hiring someone as skilled as him to assemble it is a no-brainer. I highly recommend their services to anyone looking for a hassle-free experience.",
    service: 'Fitness Equipment Assembly',
    date: 'Dec 2024',
  },
  {
    name: 'Grant R.',
    title: 'Same day response, next day service',
    review: 'Great service. Responded within minutes. Set up next day service. Showed up on time. Very professional. Excellent quality. Will use again.',
    service: 'Fitness Equipment Assembly',
    date: 'Nov 2024',
  },
  {
    name: 'Dale H.',
    title: 'Professional home gym assembly',
    review: 'Assembled the start of my home gym with ease. Very professional and does quality work. Will hire again.',
    service: 'Fitness Equipment Assembly',
    date: 'Nov 2024',
  },
  {
    name: 'Demona H.',
    title: 'Attentive and completed in a timely manner',
    review: '2EZ TEC was very attentive. He provided information on parts and his follow through was great! He did a good job and completed it in a timely manner.',
    service: 'Exercise Equipment Repair',
    date: 'Nov 2024',
  },
  {
    name: 'Jenae D.',
    title: 'Fixed Peloton for a fraction of Peloton\'s price',
    review: 'They are great. Fixed my peloton for a quarter of what peloton quoted',
    service: 'Exercise Equipment Repair',
    date: 'Oct 2024',
  },
  {
    name: 'Jacki K.',
    title: 'Excellent FreeStep Crosstrainer assembly',
    review: 'Robby did an excellent job assembling my FreeStep Crosstrainer. I highly recommend him!',
    service: 'Fitness Equipment Assembly',
    date: 'Oct 2024',
  },
  {
    name: 'John G.',
    title: 'Prompt, reasonable, quick',
    review: 'Great to do business with. Prompt response, reasonable quote and quick work. Thanks a bunch.',
    service: 'Exercise Equipment Repair',
    date: 'Sep 2024',
  },
  {
    name: 'Ketan',
    title: 'Prompt and machine perfectly repaired',
    review: 'Great experience with this firm due to their prompt responses and getting my machine perfectly repaired.',
    service: 'Exercise Equipment Repair',
    date: 'Aug 2024',
  },
  {
    name: 'Gabriel G.',
    title: 'Would give 10 stars if possible',
    review: 'Very professional and it works great was quick as well if I could id give 10 stars',
    service: 'Fitness Equipment Assembly',
    date: 'Aug 2024',
  },
  {
    name: 'Francisco V.',
    title: 'Timely and greatly done',
    review: 'Timely and greatly done.',
    service: 'Fitness Equipment Assembly',
    date: 'Jul 2024',
  },
  {
    name: 'Chandler P.',
    title: 'Saved my marriage moving a Peloton Tread Plus',
    review: "Robby single-handedly saved my marriage today. My husband and I attempted to disassemble, move and reassemble our Peloton Tread Plus last night. Now, keep in mind, this thing weighs around 600lbs and after a bit of time, frustration and many tears, we gave up. I messaged Robby today begging for help and he came out to my house within an hour and got this thing all set up and running for me! Robby was extremely professional, punctual and SO knowledgeable. We quite literally couldn't have done this without him. The next time I decide I want to move my treadmill, I'm going to call Robby because he made the new assembly so seamless. Thank you for saving us!!!",
    service: 'Fitness Equipment Assembly',
    date: 'Jul 2024',
  },
  {
    name: 'John W.',
    title: 'Excellent work when he arrived',
    review: 'Missed scheduled time but when he finally got here he was excellent.',
    service: 'Fitness Equipment Assembly',
    date: 'Jul 2024',
  },
  {
    name: 'Rob W.',
    title: 'Made sure I was satisfied before leaving',
    review: 'Professional and friendly staff. Fixed the issue quickly and made sure I was satisfied before he left.',
    service: 'Exercise Equipment Repair',
    date: 'Jul 2024',
  },
  {
    name: 'Sylvia U.',
    title: 'Great job, knowledgeable and professional',
    review: 'Robby did a great job. Very knowledgeable and professional',
    service: 'Fitness Equipment Assembly',
    date: 'Jul 2024',
  },
  {
    name: 'Taylor R.',
    title: 'Same day Smith machine service',
    review: 'We had a great experience with 2EZ TEK! They were able to come out same day and get our smith machine together and we are so grateful for that. Will definitely be using them in the future!',
    service: 'Exercise Equipment Repair',
    date: 'Jul 2024',
  },
  {
    name: 'Aiyappa M.',
    title: 'Highly recommended for all assembly',
    review: 'Excellent service provided, highly recommend for all your assembly requirements!',
    service: 'Exercise Equipment Repair',
    date: 'Jul 2024',
  },
  {
    name: 'Charles L.',
    title: 'Great experience overall',
    review: 'Great experience overall!',
    service: 'Exercise Equipment Repair',
    date: 'Jul 2024',
  },
  {
    name: 'Demetria H.',
    title: 'Fixed crooked basketball goal perfectly',
    review: 'Very helpful and reassembled my basketball goal so that it could actually stand up without falling. Plus he made it not be crooked. He offered more assistance on how to prevent future issues with its stability. I will definitely call again if I need any future help.',
    service: 'Fitness Equipment Assembly',
    date: 'Jul 2024',
  },
  {
    name: 'Rahman',
    title: 'Excellent service, responds quickly',
    review: 'Excellent service and responds quickly.',
    service: 'Exercise Equipment Repair',
    date: 'May 2024',
  },
  {
    name: 'Adrianna B.',
    title: 'Power cage with Smith machine assembled perfectly',
    review: '2EZ TEK LLC did a wonderful job assembling my power cage with smith machine and pulley system. Highly recommend!',
    service: 'Fitness Equipment Assembly',
    date: 'Apr 2024',
  },
  {
    name: 'Rebecca',
    title: 'Showed up quick, great communication',
    review: 'Showed up quick, great communication & fixed my issue!',
    service: 'Exercise Equipment Repair',
    date: 'Apr 2024',
  },
  {
    name: 'Anup R.',
    title: 'Great service',
    review: 'Great service.',
    service: 'Exercise Equipment Repair',
    date: 'Feb 2024',
  },
  {
    name: 'Tracey L.',
    title: 'Elliptical fixed in minutes, no new parts',
    review: 'Robby fixed my elliptical in a few minutes without any new parts, it made my day!',
    service: 'Exercise Equipment Repair',
    date: 'Feb 2024',
  },
  {
    name: 'Ethan L.',
    title: 'Great experience and knowledge',
    review: 'Great experience and knowledge.',
    service: 'Exercise Equipment Repair',
    date: 'Feb 2024',
  },
  {
    name: 'Nikul S.',
    title: 'Shared tips and kept workspace clean',
    review: 'I am delighted to give Robby, our treadmill technician, a well-deserved 5-star review. Not only did he assemble our elliptical swiftly, but he also offered a fantastic price for his services. His professionalism was evident as he maintained a clean work area throughout the process. What truly sets Robby apart is his dedication to customer satisfaction. He shared valuable tips and best practices, ensuring we get the most out of our equipment. Highly recommended for top-notch service!',
    service: 'Exercise Equipment Repair',
    date: 'Feb 2024',
  },
  {
    name: 'Mae C.',
    title: "Couldn't ask for better",
    review: "Great and couldn't ask for better",
    service: 'Exercise Equipment Repair',
    date: 'Feb 2024',
  },
  {
    name: 'Al R.',
    title: 'Best quote, tidied up after the job',
    review: 'Robert did an amazing job installing my home gym. Best quote and service. He tidied up the place after the assembly. Highly recommend him for any of your assembly needs',
    service: 'Fitness Equipment Assembly',
    date: 'Dec 2023',
  },
  {
    name: 'Laura H.',
    title: 'Very pleased with the service',
    review: 'Very pleased with this service!',
    service: 'Exercise Equipment Repair',
    date: 'Nov 2023',
  },
  {
    name: 'Sean M.',
    title: 'Will hire again and refer others',
    review: 'Will hire again and refer business their way.',
    service: 'Fitness Equipment Assembly',
    date: 'Nov 2023',
  },
  {
    name: 'Jeremy R.',
    title: 'Great company',
    review: 'Great company.',
    service: 'Exercise Equipment Repair',
    date: 'Oct 2023',
  },
  {
    name: 'Gordon C.',
    title: 'Elliptical and TV mount, no hesitation',
    review: 'Robby was great, and I would not hesitate to use him again in the future. He assembled my elliptical and mounted a brick screen TV for me.',
    service: 'Fitness Equipment Assembly',
    date: 'Oct 2023',
  },
  {
    name: 'Jacey B.',
    title: 'Great experience',
    review: 'Great experience!',
    service: 'Fitness Equipment Assembly',
    date: 'Oct 2023',
  },
  {
    name: 'Leslie S.',
    title: 'Great diagnosis, part on order',
    review: 'Robby did a great job diagnosing the problem. Waiting on the part to complete the repair.',
    service: 'Exercise Equipment Repair',
    date: 'Sep 2023',
  },
  {
    name: 'Naveen Y.',
    title: 'Helpful and quickly solved the problem',
    review: 'Very helpful and quickly solved the problem',
    service: 'Exercise Equipment Repair',
    date: 'Sep 2023',
  },
  {
    name: 'Samantha A.',
    title: 'Wonderful service',
    review: 'Wonderful!',
    service: 'Exercise Equipment Repair',
    date: 'Sep 2023',
  },
  {
    name: 'Norman B.',
    title: 'Knowledgeable, nice and friendly',
    review: 'Our repair tech was very knowledgeable, nice and friendly. We would use their services again if needed.',
    service: 'Exercise Equipment Repair',
    date: 'Sep 2023',
  },
  {
    name: 'Cecilia C.',
    title: 'Great to work with, very communicative',
    review: 'Robby was great to work with! He took care of the issue and was very communicative!',
    service: 'Exercise Equipment Repair',
    date: 'Aug 2023',
  },
  {
    name: 'Jana S.',
    title: 'Great work both times on our elliptical',
    review: '2EZ TEK LLC has worked on our Proforma elliptical twice and has done a great job each time.',
    service: 'Exercise Equipment Repair',
    date: 'Aug 2023',
  },
  {
    name: 'James D.',
    title: 'Quick turnaround, true professional',
    review: 'Very great service and quick turnaround. Robbie was a true Professional.',
    service: 'Exercise Equipment Repair',
    date: 'Aug 2023',
  },
  {
    name: 'Bill H.',
    title: 'Great contractor, would hire again',
    review: 'great contractor would hire again',
    service: 'Fitness Equipment Assembly',
    date: 'Aug 2023',
  },
  {
    name: 'Cynthia C.',
    title: 'Excellent experience',
    review: 'Excellent experience!',
    service: 'Fitness Equipment Assembly',
    date: 'Jul 2023',
  },
  {
    name: 'Verified Customer',
    title: 'Great team, thankful for the efforts',
    review: 'Great team! Thankful for all the efforts!',
    service: 'Fitness Equipment Assembly',
    date: 'Jul 2023',
  },
  {
    name: 'Tamaron S.',
    title: 'Insightful and helpful at great value',
    review: 'Great experience working with the company. Very insightful and helpful for a great value. I would highly recommend!',
    service: 'Exercise Equipment Repair',
    date: 'Jul 2023',
  },
  {
    name: 'Rehnuma A.',
    title: 'Diagnosed a two-year-old elliptical problem',
    review: "Robby and his associate were very helpful. My elliptical had been broken for about two years and was basically unusable unless riden on an incline. Robby analyzed the situation and took his time to listen to our concerns and examine the problem from every angle. He was able to inform us that our issue was a manufacturing problem and helped us move forward in the next step. I would recommend their services to anyone looking for repairs for gym equipment!!",
    service: 'Exercise Equipment Repair',
    date: 'Jul 2023',
  },
  {
    name: 'Ryan C.',
    title: 'Excellent work and super fast',
    review: 'Excellent work and super fast',
    service: 'Fitness Equipment Assembly',
    date: 'Jul 2023',
  },
  {
    name: 'Jay B.',
    title: 'Extremely professional and responsive',
    review: 'Extremely professional and responsive. He did a great job.',
    service: 'Fitness Equipment Assembly',
    date: 'Jul 2023',
  },
  {
    name: 'Ron B.',
    title: 'Our go-to company for gym service',
    review: "First of Robbie responded very quickly to my request. When he and his team arrived for the job they showed up with a smile and ready to work. They quickly took down our equipment in less time than stated and did a great job in doing it. Robbie has an awesome attitude and aims to please his customers! Don't sleep on this company, 2EZ TEK will always be our go-to company for any gym repair service!!",
    service: 'Fitness Equipment Assembly',
    date: 'Jul 2023',
  },
  {
    name: 'Brandon S.',
    title: 'All around excellent',
    review: 'All around excellent',
    service: 'Fitness Equipment Assembly',
    date: 'Jun 2023',
  },
  {
    name: 'Verified Customer',
    title: 'Great service, very friendly',
    review: 'Great service by the technician, and very friendly',
    service: 'Exercise Equipment Repair',
    date: 'Jun 2023',
  },
  {
    name: 'Reza A.',
    title: 'Honest about what maintenance you need',
    review: "They did a great job explaining me about my product and unnecessary maintenance that I don't need.",
    service: 'Exercise Equipment Repair',
    date: 'Jun 2023',
  },
  {
    name: 'Theis R.',
    title: 'Would not hesitate to use again',
    review: 'Would not hesitate to use this service again.',
    service: 'Exercise Equipment Repair',
    date: 'Jun 2023',
  },
  {
    name: 'Jeanette',
    title: 'Awesome, offered great maintenance advice',
    review: 'Robby was awesome- he came out and fixed machine and offered great maintenance advice.',
    service: 'Exercise Equipment Repair',
    date: 'Jun 2023',
  },
  {
    name: 'Verified Customer',
    title: 'Quickly diagnosed, prompt and professional',
    review: 'The issue with my treadmill was quickly diagnosed. Service was prompt and professional.',
    service: 'Exercise Equipment Repair',
    date: 'Jun 2023',
  },
  {
    name: 'Linda G.',
    title: 'Fast and efficient',
    review: 'He was fast and efficient and will use again if needed!',
    service: 'Exercise Equipment Repair',
    date: 'Jun 2023',
  },
  {
    name: 'Matt Z.',
    title: 'Everything worked as expected',
    review: 'Everything worked as expected.',
    service: 'Fitness Equipment Assembly',
    date: 'Jun 2023',
  },
  {
    name: 'Siyan F.',
    title: 'Solved it the most cost-efficient way',
    review: '2EZ TEK was very professional and solved my equipment problem in the most cost efficient way.',
    service: 'Fitness Equipment Assembly',
    date: 'Jun 2023',
  },
  {
    name: 'Michael G.',
    title: 'Reasonable rates, will use again',
    review: "I cannot say enough good things about my experience with 2EZ Tek assembling my elliptical. Robby did a great job assembling the elliptical very quickly and professionally. His responsiveness was great and he was an interesting guy to talk to. His rates were very reasonable. I'll definitely use him in the future.",
    service: 'Fitness Equipment Assembly',
    date: 'Jun 2023',
  },
  {
    name: 'Carla N.',
    title: 'Professional, fast and pleasant',
    review: 'Robby is very professional and he works fast. He is a pleasant person to work with. I would definitely recommend him to others.',
    service: 'Exercise Equipment Repair',
    date: 'May 2023',
  },
  {
    name: 'Kathy B.',
    title: 'Found the problem quickly',
    review: "He was on time & found problem quickly. Unfortunately it was a part so it was expensive. Cheaper than buying a new treadmill",
    service: 'Exercise Equipment Repair',
    date: 'May 2023',
  },
  {
    name: 'Shariot M.',
    title: 'Worked in the rain to get the job done',
    review: "Where do I begin? The service is top-notch. Robby arrived early and was very professional and courteous. He put together this new hoop and disassembled the old one for us, even with the sudden downpour of rain. Yes, he worked in the rain. After the rain stopped, he continued to clean up and put things where I wanted them to go. 2EZ TEK comes highly recommended by me, I would definitely hire for other jobs. BTW, the original work he did on the old basketball hoop is still intact after 3 years of crazy weather!!",
    service: 'Fitness Equipment Assembly',
    date: 'May 2023',
  },
  {
    name: 'Kevin G.',
    title: 'Speedy and perfect service',
    review: 'Received speedy excellent service. Perfect. Very highly recommend.',
    service: 'Fitness Equipment Assembly',
    date: 'May 2023',
  },
  {
    name: 'Martha R.',
    title: 'Very knowledgeable, treadmill works beautifully',
    review: "Today we called 2EZ TEK LLC to help with servicing my treadmill. Unsure of what my treadmill exactly needed. My husband briefly shared with him what was going on. He was very knowledgeable in explaining what the treadmill needed. Thanks to 2EZ TEK LLC my Treadmill is working beautiful! I Would definitely recommend him to anyone. He's a very nice guy.",
    service: 'Exercise Equipment Repair',
    date: 'May 2023',
  },
  {
    name: 'Scott R.',
    title: 'Went far beyond identifying the problem',
    review: 'He did an excellent job in helping me out in identifying the problems and went way far beyond in helping me out.',
    service: 'Exercise Equipment Repair',
    date: 'May 2023',
  },
  {
    name: 'Jake',
    title: 'Fixed treadmill and helped with spin bike too',
    review: 'Super nice guy, very knowledgeable. Got my treadmill up and running and even helped with my spin bike',
    service: 'Exercise Equipment Repair',
    date: 'May 2023',
  },
  {
    name: 'Verified Customer',
    title: 'Fast response, same day service',
    review: 'Robby was fast to respond and provided same day service. Definitely recommend him for treadmill service.',
    service: 'Exercise Equipment Repair',
    date: 'May 2023',
  },
  {
    name: 'Daisy K.',
    title: 'Multi-hour all-in-one trainer, great work',
    review: 'Great work on a All-in-One Trainer that took several hours. Would definitely hire again.',
    service: 'Fitness Equipment Assembly',
    date: 'Apr 2023',
  },
  {
    name: 'Ruben C.',
    title: 'Transparent with great communication',
    review: 'Robbie was awesome! He took care of us, was transparent and had great communication. I will definitely be recommending him and 2EZ TEK to anyone in the future!',
    service: 'Exercise Equipment Repair',
    date: 'Apr 2023',
  },
  {
    name: 'Andy F.',
    title: 'Excellent all around',
    review: 'Excellent all around!',
    service: 'Exercise Equipment Repair',
    date: 'Apr 2023',
  },
  {
    name: 'Jessica M.',
    title: 'Removed old, assembled new, within 2 hours',
    review: 'Excellent communication. I needed a treadmill removed and new one assembled. It was completed within two hours of the request! Great service!',
    service: 'Exercise Equipment Repair',
    date: 'Apr 2023',
  },
  {
    name: 'Anita R.',
    title: 'Patient, professional, worked around our schedule',
    review: "Robbie was extremely understanding, patient, and professional in figuring out what was wrong with our Sole treadmill. We'd had it dissassembled before a move and it just wouldn't run without issue since reassembling. He was easy to communicate with in setting up the appointment and worked around our schedule which has been erratic lately! Pleasant and efficient. Keeping his card handy to pass on to others we know! We'd definitely recommend.",
    service: 'Exercise Equipment Repair',
    date: 'Apr 2023',
  },
  {
    name: 'Casie L.',
    title: 'Professional, knowledgeable, very satisfied',
    review: 'Very professional and knowledgeable. Very satisfied with his work.',
    service: 'Exercise Equipment Repair',
    date: 'Apr 2023',
  },
  {
    name: 'Taylor E.',
    title: 'Shared tips for keeping equipment in shape',
    review: 'Rob was outstanding with communication, scheduling, and showed great expertise with repairing my treadmill. Rob was very professional, knowledgeable, and kind to share tips for keeping my treadmill in good condition. Would highly recommend him to others!',
    service: 'Exercise Equipment Repair',
    date: 'Apr 2023',
  },
  {
    name: 'Mona S.',
    title: 'Honored quoted price despite complex job',
    review: 'He came in time and charged me the same amount even though the work turned to be quite complex since my treadmill is quite old.',
    service: 'Exercise Equipment Repair',
    date: 'Apr 2023',
  },
  {
    name: 'Derick J.',
    title: 'Very knowledgeable',
    review: 'Very knowledgeable.',
    service: 'Exercise Equipment Repair',
    date: 'Apr 2023',
  },
  {
    name: 'Jessie G.',
    title: 'Well done',
    review: 'Well done.',
    service: 'Fitness Equipment Assembly',
    date: 'Apr 2023',
  },
  {
    name: 'Ganesh B.',
    title: 'Now our go-to for all fitness equipment',
    review: 'Rob was outstanding starting with scheduling the appointment and everything with regard to servicing our fitness equipments. He was very engaging and shared with us a few things we could do for preventive maintenance, which we really appreciated. Overall a very pleasant experience. Rob is now our go-to-guy for any future needs. We will also recommend him to others in a heartbeat!',
    service: 'Exercise Equipment Repair',
    date: 'Apr 2023',
  },
  {
    name: 'Treyon M.',
    title: 'Professional, efficient, no mess left behind',
    review: 'Professional, efficient and friendly service! Excellent work and no mess left behind. Easy to schedule and coordinate. Great work!',
    service: 'Exercise Equipment Repair',
    date: 'Mar 2023',
  },
  {
    name: 'Amy D.',
    title: 'Diagnosed it over the phone, then confirmed',
    review: "Robbie basically knew what was wrong with my treadmill just based on what I told him on the phone. When he arrived to check it out, he was right! Since it was a console issue that was under warranty from the manufacturer, he was able to get them on the phone and the part ordered and shipped to me for FREE! When the part arrives, he will come back and install it. I'm very pleased thus far! Robbie is very knowledgeable and professional. I was so tired of getting the run-around.",
    service: 'Exercise Equipment Repair',
    date: 'Mar 2023',
  },
  {
    name: 'Claudia M.',
    title: 'Went above and beyond on repair and maintenance',
    review: 'Robby was a fantastic technician and went above and beyond in his repair and maintenance. I will want to have Robbie take care of all my tech needs like this! Thank you Thumbtack for getting me to 2EZ TEK LLC!',
    service: 'Exercise Equipment Repair',
    date: 'Mar 2023',
  },
  {
    name: 'Jamie M.',
    title: 'Responded in minutes, fixed same afternoon',
    review: 'Five Stars! He responded to my request in a few minutes, came out to fix my elliptical that afternoon, was friendly and knowledgeable, and did great work!',
    service: 'Exercise Equipment Repair',
    date: 'Mar 2023',
  },
  {
    name: 'Edwin E.',
    title: 'The best and very professional',
    review: 'Will recommend. The best and very professional. Will definitely use his again.',
    service: 'Exercise Equipment Repair',
    date: 'Mar 2023',
  },
  {
    name: 'Dan A.',
    title: 'A+ service and quick turnaround',
    review: 'A+ service and very quick turn around time. Would recommend 2EZ TEK to anyone and will be using them again for any future equipment set up/maintenance.',
    service: 'Fitness Equipment Assembly',
    date: 'Mar 2023',
  },
  {
    name: 'Kevin C.',
    title: 'Timely, professional treadmill service',
    review: 'My experience with 2EZ Tek was fantastic. He was timely, professional, and did a great job servicing my treadmill. I will definitely be using them again!',
    service: 'Exercise Equipment Repair',
    date: 'Mar 2023',
  },
  {
    name: 'Andy W.',
    title: 'Complete job finished in under an hour',
    review: 'Great work. Quick response complete job finished in less than an hour!',
    service: 'Exercise Equipment Repair',
    date: 'Mar 2023',
  },
  {
    name: 'Sashi S.',
    title: 'Overall a great experience',
    review: 'Overall, a great experience',
    service: 'Fitness Equipment Assembly',
    date: 'Mar 2023',
  },
  {
    name: 'Kristen H.',
    title: 'Responded in 30 seconds, came with part ready',
    review: 'This was a great company to work with. Ronnie returned my first contact message within 30 seconds, and had my exercise bike fixed quickly. He knew just what the issue was by my phone description, and came with the part ready for repair. I am up and running again in NO TIME AT ALL!! Will definitely use him for future service and repair on this bike.',
    service: 'Exercise Equipment Repair',
    date: 'Mar 2023',
  },
  {
    name: 'Easter M.',
    title: 'Knew what to do and answered every question',
    review: 'Very professional! I appreciate that he knew what he needed to do, got his tools and repaired my treadmill, he also was patient with answering my questions.',
    service: 'Exercise Equipment Repair',
    date: 'Mar 2023',
  },
  {
    name: 'Verified Customer',
    title: 'Great, would hire again',
    review: 'Great! Would hire again',
    service: 'Fitness Equipment Assembly',
    date: 'Mar 2023',
  },
  {
    name: 'John C.',
    title: 'Great to meet, looking forward to the estimate',
    review: 'Great to meet you and I look forward seeing the estimate',
    service: 'Exercise Equipment Repair',
    date: 'Mar 2023',
  },
  {
    name: 'Lincoya Y.',
    title: 'Fast, efficient and very professional',
    review: 'Fast efficient excellent service very professional',
    service: 'Exercise Equipment Repair',
    date: 'Mar 2023',
  },
  {
    name: 'Alexander W.',
    title: 'Makes fixing treadmills look easy',
    review: "Robby is an absolute professional and makes fixing treadmills look easy.. too easy in fact! I couldn't be happier with the work he did replacing my walking belt and troubleshooting my machine. Will definitely recommend his company and call him the next time I need help.",
    service: 'Exercise Equipment Repair',
    date: 'Mar 2023',
  },
  {
    name: 'Verified Customer',
    title: 'Assembled it and explained how it works',
    review: 'These guys were really good. Not only they assembled it but they explained the working of the equipment as well.',
    service: 'Fitness Equipment Assembly',
    date: 'Mar 2023',
  },
  {
    name: 'Ray M.',
    title: 'Fixed my problem with ease',
    review: 'Excellent service. Fixed my problem with ease.',
    service: 'Exercise Equipment Repair',
    date: 'Sep 2022',
  },
  {
    name: 'Muslim N.',
    title: 'Great customer service and attitude',
    review: 'The Tech was great very good and good customer service and attitude',
    service: 'Fitness Equipment Assembly',
    date: 'Sep 2022',
  },
  {
    name: 'Eric B.',
    title: 'Great experience, highly recommended',
    review: 'Great experience, highly recommended',
    service: 'Exercise Equipment Repair',
    date: 'Sep 2022',
  },
  {
    name: 'Barry I.',
    title: 'Excellent work, well done',
    review: 'Excellent work well done',
    service: 'Fitness Equipment Assembly',
    date: 'Aug 2022',
  },
  {
    name: 'Verified Customer',
    title: 'Very professional, great job',
    review: 'very professional and did a great job. I highly recommend',
    service: 'Exercise Equipment Repair',
    date: 'Aug 2022',
  },
  {
    name: 'Jan S.',
    title: 'Tackled a very difficult upstairs gym job',
    review: 'It was a very difficult job and Robbie and David did a great job putting our gym together upstairs.',
    service: 'Fitness Equipment Assembly',
    date: 'Aug 2022',
  },
  {
    name: 'Jeff P.',
    title: 'Smith machine built on time as promised',
    review: 'Did a great job putting together my Smith Machine. Communication was great throughout the process and he showed up when he said he would and finished within the timeframe he gave me. Highly recommend!',
    service: 'Fitness Equipment Assembly',
    date: 'Aug 2022',
  },
  {
    name: 'Wendy C.',
    title: 'Above and beyond to resolve my issue',
    review: 'Robby is very friendly and personable. I received a rapid response to my request. All my questions were answered, and he went above and beyond to resolve my issue. Excellent customer service still exists.',
    service: 'Exercise Equipment Repair',
    date: 'Aug 2022',
  },
  {
    name: 'Daniel M.',
    title: 'Assembled boxing equipment with limited instructions',
    review: 'Robby was a God send. He came out and set up our Boxing equipment. Did an excellent job even though the instructions were extremely limited. He was on time, efficient and gave some good tips upon leaving. If we decide to add any new equipment he and his team will be the first call.',
    service: 'Fitness Equipment Assembly',
    date: 'Aug 2022',
  },
  {
    name: 'Norman S.',
    title: 'Exceptional service, very professional',
    review: 'Exceptional service, very professional',
    service: 'Fitness Equipment Assembly',
    date: 'Aug 2022',
  },
  {
    name: 'Pamela J.',
    title: 'Came within an hour of request',
    review: 'Fast service. Great work! Came within an hour or request.',
    service: 'Fitness Equipment Assembly',
    date: 'Aug 2022',
  },
  {
    name: 'Kassandra D.',
    title: '20-minute run with zero issues after repair',
    review: 'Great service. My treadmill is ready to go. I already did a 20min run and had 0 issues. Will definitely recommend Robby to get the job done! Loved how fast it was able to get my treadmill up and running. Thanks Robby!',
    service: 'Fitness Equipment Assembly',
    date: 'Aug 2022',
  },
  {
    name: 'Greg P.',
    title: 'Resolved treadmill error code over the phone',
    review: 'My treadmill was giving me an error code. Out of warranty the manufacturer site did not resolve issue. Robby was able to help me over the phone to resolve my issue for a phone consultation. This was a great help since I know nothing about treadmill repair.',
    service: 'Exercise Equipment Repair',
    date: 'Aug 2022',
  },
  {
    name: 'Debi T.',
    title: 'The definition of customer service',
    review: 'Robby was the absolute definition of customer service and professionalism. He was responsive, punctual and knowledgeable. Also, a very polite and friendly guy. We highly recommend 2EZ TEK LLC for exercise equipment assembly and moving!',
    service: 'Fitness Equipment Assembly',
    date: 'Aug 2022',
  },
  {
    name: 'Billy G.',
    title: 'Showed up on time, finished as promised',
    review: 'Robby was Great. Showed up on time and finish when he said he would. Will definitely recommend him and use again when needed.',
    service: 'Fitness Equipment Assembly',
    date: 'Jul 2022',
  },
  {
    name: 'Festus A.',
    title: 'Job was harder than described, still delivered',
    review: 'Robbie is very good at what he does. He came and saw that my treadmill installation was way more than I had described. But he still made it work. Extremely happy with his service and the installation',
    service: 'Fitness Equipment Assembly',
    date: 'Jul 2022',
  },
  {
    name: 'Jim M.',
    title: 'On time, recommend for TX, AR, LA',
    review: 'Robby and his team did excellent work today for one of my customers. He arrived on time, went right to work assembly one of my stationary bikes. Looks and works great. Customer is happy, I am happy. I recommend him to anyone in the area and will use him again in the TX, AR, LA area.',
    service: 'Fitness Equipment Assembly',
    date: 'Jul 2022',
  },
  {
    name: 'Shawnte B.',
    title: 'On time, professional, a joy to meet',
    review: "I can't say enough good things about the service I received. I needed someone to replace a treadmill belt. He was on time, professional, reasonable, and was just a joy to meet. This was excellent customer service!",
    service: 'Exercise Equipment Repair',
    date: 'Jul 2022',
  },
  {
    name: 'Ravi S.',
    title: 'Awesome job, well done',
    review: 'Awesome job well done. Thank you.',
    service: 'Fitness Equipment Assembly',
    date: 'Jul 2022',
  },
  {
    name: 'Nidaa',
    title: 'Best price, on time, done quickly',
    review: 'Very happy with the service provided to build my sons outdoor basketball net. Best price offered very reasonable. Arrived on time and got the task completed very quickly. Friendly service will definitely recommend and use again for more services',
    service: 'Fitness Equipment Assembly',
    date: 'Jul 2022',
  },
  {
    name: 'Besem O.',
    title: 'Punctual and great job on the repair',
    review: 'My treadmill was bad and Orlando did a great job fixing it. He was punctual and did a great job.',
    service: 'Exercise Equipment Repair',
    date: 'Jul 2022',
  },
  {
    name: 'Angela H.',
    title: 'Responsive, professional and economical',
    review: 'This team is awesome! responsive, professional and economical! I definitely would use them for any and all Gym equipment to do\'s!! Thanks Orlando!, a happy customer',
    service: 'Fitness Equipment Assembly',
    date: 'Jul 2022',
  },
  {
    name: 'Willie T.',
    title: '5 stars top to bottom',
    review: 'Very professional and right on time 5 stars top to bottom',
    service: 'Fitness Equipment Assembly',
    date: 'Jul 2022',
  },
  {
    name: 'Kim',
    title: 'True professional, assembled rower quickly',
    review: "I got an almost immediate response to my request. We set up appt for the next day. Robbie was a true professional who put together my rower quickly and accurately. He shared knowledge of my product and it's warranty. I would definitely contact him again without hesitation. Highly recommend!",
    service: 'Fitness Equipment Assembly',
    date: 'Jul 2022',
  },
  {
    name: 'Sameer V.',
    title: 'Knowledgeable and professional service',
    review: 'Very good service highly knowledgeable and professional',
    service: 'Fitness Equipment Assembly',
    date: 'Jul 2022',
  },
  {
    name: 'Verified Customer',
    title: 'Professional and quick, highly recommend',
    review: 'Very professional and quick. Would highly recommend.',
    service: 'Fitness Equipment Assembly',
    date: 'Jul 2022',
  },
  {
    name: 'Nancy F.',
    title: 'Super quick response and great professionalism',
    review: 'Super quick response and great professionalism.',
    service: 'Exercise Equipment Repair',
    date: 'Jul 2022',
  },
  {
    name: 'Walter W.',
    title: 'Absolutely the best',
    review: 'Absolutely the Best!!!! Truly glad I went with them...will definitely be using them again...Great Job!!!!',
    service: 'Fitness Equipment Assembly',
    date: 'Jul 2022',
  },
  {
    name: 'Roy W.',
    title: 'Tested to make sure everything was perfect',
    review: 'Technician was very pleasant and knowledgeable. Assembled and tested to make sure everything was perfect.',
    service: 'Exercise Equipment Repair',
    date: 'Jul 2022',
  },
  {
    name: 'Jeff B.',
    title: 'Very friendly and knowledgeable',
    review: 'Very friendly and knowledgeable',
    service: 'Exercise Equipment Repair',
    date: 'Jul 2022',
  },
  {
    name: 'Varadha R.',
    title: 'Good knowledgeable technician',
    review: 'Good knowledgeable technician',
    service: 'Exercise Equipment Repair',
    date: 'Jun 2022',
  },
  {
    name: 'Ely K.',
    title: 'Knew exactly what he was doing',
    review: 'He knew exactly what he was doing. Work was great. Would highly recommend!',
    service: 'Fitness Equipment Assembly',
    date: 'Jun 2022',
  },
  {
    name: 'Barry I.',
    title: 'Will use services in the future',
    review: 'Excellent service done and will use his services in the future',
    service: 'Fitness Equipment Assembly',
    date: 'May 2022',
  },
  {
    name: 'Jana S.',
    title: 'Punctual, efficient and professional',
    review: 'Was punctual, efficient, professional and did a great job!',
    service: 'Fitness Equipment Assembly',
    date: 'May 2022',
  },
  {
    name: 'Debbie',
    title: 'Sunday service on short notice',
    review: 'Robby came out on a Sunday with short notice and easily fixed my new treadmill. Great service and will definitely call him again when the need arises. 5 Star for sure!',
    service: 'Exercise Equipment Repair',
    date: 'May 2022',
  },
  {
    name: 'Heath D.',
    title: 'Level of transparency rarely seen',
    review: "My experience working with Robby towards a solution to our equipment issue was top notch. Robby displayed exceptional attention to detail, as well as a level of professionalism and (most importantly) transparency I haven't experienced as a consumer in quite some time. I would confidently and willingly refer anyone I know to Robby and 2EZ TEK LLC. That is the level of confidence I have in Robby's approach to business and customer service. He was exceptional.",
    service: 'Exercise Equipment Repair',
    date: 'May 2022',
  },
  {
    name: 'Charlie P.',
    title: 'Explained parts and maintenance after job',
    review: 'Robby with 2EZ TEK LLC was prompt, pleasant, professional and efficient. He was also incredibly knowledgeable about our commercial grade treadmill. He was very quick with the disassembly, which we desperately needed to meet a next day move date. After disassembly he took the time to explain the parts and their operation and how best to maintain the equipment. Very much appreciated.',
    service: 'Exercise Equipment Repair',
    date: 'May 2022',
  },
  {
    name: 'Ricky S.',
    title: 'Three trips, only charged for one',
    review: 'Robby came to our house to replace the treadmill belt. After replacing the belt, it was discovered another belt to the motor needed replacing as well. Robby had to order that belt, and when it arrived he came back over to replace. However, once at our house, he realized they sent the wrong belt. He had to reorder it again and make a third trip to our house. After three trips, he still just charged for one trip. He apologized for it taking so long.',
    service: 'Exercise Equipment Repair',
    date: 'May 2022',
  },
  {
    name: 'Meeta B.',
    title: 'Basketball goal assembled, quick job',
    review: "I highly recommend this company! Needed a basketball goal assembled and it didn't take him long to do it. I would def use them again!!",
    service: 'Fitness Equipment Assembly',
    date: 'May 2022',
  },
  {
    name: 'Bob F.',
    title: 'Excellent communicator, very professional',
    review: 'Excellent communicator. Very professional.',
    service: 'Exercise Equipment Repair',
    date: 'May 2022',
  },
  {
    name: 'Sergio C.',
    title: 'Had the part on hand, fixed on the spot',
    review: 'The tech called me to let me know his ETA. Ran some tests on the treadmill determined what the problem was. He had the part in stock replaced it and I was good to go.',
    service: 'Exercise Equipment Repair',
    date: 'May 2022',
  },
  {
    name: 'Michael',
    title: 'Took extra time to clean and service',
    review: 'Robbie my tech was fantastic. He took the extra time to really clean and service the elliptical. The machine runs like brand new. Well worth the call. Will use him for all my needs and recommend him highly',
    service: 'Exercise Equipment Repair',
    date: 'May 2022',
  },
  {
    name: 'Prashanth N.',
    title: 'Best in the business, home gym under 2 hours',
    review: 'Robby and co are awesome.. best in the business. Got the home gym installed in less than 2 hours.',
    service: 'Fitness Equipment Assembly',
    date: 'Apr 2022',
  },
  {
    name: 'Verified Customer',
    title: 'Quick, professional and knowledgeable',
    review: 'Quick response, professional, knowledgeable, and great work. I will recommend to anyone who needs fitness equipment installed, moved or disassembled',
    service: 'Fitness Equipment Assembly',
    date: 'Apr 2022',
  },
  {
    name: 'Michele F.',
    title: 'Very pleasant and professional',
    review: 'Very pleasant and professional.',
    service: 'Fitness Equipment Assembly',
    date: 'Apr 2022',
  },
  {
    name: 'Bryan',
    title: 'Super nice, very quick with the setup',
    review: 'Super nice, cool guy! Very quick with the setup and done right, will definitely use again.',
    service: 'Fitness Equipment Assembly',
    date: 'Apr 2022',
  },
  {
    name: 'Verified Customer',
    title: 'Treadmill repair perfectly done and neat',
    review: 'Treadmill repair was perfectly done. Very professional and neat!!!',
    service: 'Exercise Equipment Repair',
    date: 'Apr 2022',
  },
  {
    name: 'Devia W.',
    title: 'Did in an hour what would take us 5-6',
    review: 'EZ TEK did in a little over an hour what would have easily taken us 5-6 hours. The response time, as well as the price point was great. I definitely recommend them for ANY fitness equipment assembly job, large or small.',
    service: 'Fitness Equipment Assembly',
    date: 'Apr 2022',
  },
  {
    name: 'Kevin D.',
    title: 'Super fast, responsive, very nice',
    review: 'Robby was Great! Super fast, responsive, very nice! Will be using again!!',
    service: 'Fitness Equipment Assembly',
    date: 'Apr 2022',
  },
  {
    name: 'Prashanth N.',
    title: 'Basketball hoop installed quickly',
    review: 'The service was fast and prompt. I needed to have my basketball hoop installed.',
    service: 'Fitness Equipment Assembly',
    date: 'Mar 2022',
  },
  {
    name: 'Nicholas B.',
    title: 'On time and completed quickly, correctly',
    review: 'Excellent work, arrived on time and completed the work quickly and correctly, very nice guy, thank you!',
    service: 'Fitness Equipment Assembly',
    date: 'Mar 2022',
  },
  {
    name: 'Susanne B.',
    title: 'Immediate contact, could not be happier',
    review: "Robby immediately contacted me to set up an appointment. He was very professional and knowledgeable. I couldn't have been happier with the service. Will definitely use them again.",
    service: 'Fitness Equipment Assembly',
    date: 'Mar 2022',
  },
  {
    name: 'Regan D.',
    title: 'Basketball goal assembled very fast',
    review: "I am very happy I selected 2EZ TEK LLC, he was very professional, knowledgeable, and was able to put together my son's basketball goal very fast. I will be using the company again and you should as well.",
    service: 'Fitness Equipment Assembly',
    date: 'Mar 2022',
  },
  {
    name: 'Robert M.',
    title: 'NBA hoop assembled in under an hour',
    review: 'Robby, was great! He assembled my kids NBA portable basketball hoop in less than 1 hour. Very professional and I would absolutely refer him to family and Friends.',
    service: 'Fitness Equipment Assembly',
    date: 'Mar 2022',
  },
  {
    name: 'Angel P.',
    title: 'Assembled basketball hoop in 30 minutes solo',
    review: "We needed our Basketball Hoop assembled asap for some outside fun for our 12 year old during spring break. Robby responded back right away and came out the next morning. This hoop had a lot of others stressing about putting it together. He assembled it in about 30 minutes by himself. He is professional and very skilled and good at what he does. My son is out enjoying his day. Thanks Robby Blessings",
    service: 'Fitness Equipment Assembly',
    date: 'Mar 2022',
  },
  {
    name: 'San S.',
    title: 'Absolutely would recommend',
    review: 'Great service!! Absolutely would recommend!',
    service: 'Fitness Equipment Assembly',
    date: 'Mar 2022',
  },
  {
    name: 'Adam R.',
    title: 'Went the extra mile, best Thumbtack experience',
    review: 'Good man, great service, went extra miles. It was one of my best experiences in Thumbtack. Absolutely recommend him.',
    service: 'Exercise Equipment Repair',
    date: 'Mar 2022',
  },
  {
    name: 'Bradley S.',
    title: 'Quick responses, very accommodating',
    review: "Great job, quick to respond and answer questions, and very accommodating. Clearly he knows what he is doing. I'd recommend him highly and use him again myself.",
    service: 'Fitness Equipment Assembly',
    date: 'Mar 2022',
  },
  {
    name: 'David F.',
    title: 'Veteran technician, great experience',
    review: 'I had a issue with my new Assault Runner Pro and 2 EZ Tek was able to resolve the problem. Robby came out and was a super nice guy, former veteran and very knowledgeable. Great experience!',
    service: 'Exercise Equipment Repair',
    date: 'Mar 2022',
  },
  {
    name: 'Adrienne B.',
    title: 'Excellent work, kept in my contacts',
    review: 'Mr. Robby came and got the job! Excellent work! I will definitely keep him in my contacts',
    service: 'Fitness Equipment Assembly',
    date: 'Mar 2022',
  },
  {
    name: 'Chris M.',
    title: 'Great service, highly recommend',
    review: 'Robby provided Great service. Highly recommend',
    service: 'Fitness Equipment Assembly',
    date: 'Feb 2022',
  },
  {
    name: 'Vivian M.',
    title: 'Responded immediately, same day assembly',
    review: 'Robby responded to my inquiry almost immediately and was able to come set up my NordicTrack treadmill same day! He did an amazing and efficient job and truly helped me out! I could never have set this up on my own. Highly recommend!!',
    service: 'Fitness Equipment Assembly',
    date: 'Feb 2022',
  },
  {
    name: 'Mike F.',
    title: 'Friendly, professional, ready in an hour',
    review: 'Robby assembled my new Nordic Track treadmill. He was friendly, professional and had it ready to use in about an hour. Nice guy, great job!',
    service: 'Fitness Equipment Assembly',
    date: 'Feb 2022',
  },
]
