export type Review = {
  name: string
  role: string
  title: string
  review: string
  tag: string
  date: string
}

export const googleReviews: Review[] = [
  {
    name: 'Chad F',
    role: 'Repeat Client · Multiple Homes',
    title: 'My go-to for anything fitness assembly',
    review: 'This company is my go-to source for anything fitness assembly and help. I have used them multiple times in different homes. They have gone out of their way to make sure I get taken care of. The owner especially has been amazing to deal with.',
    tag: 'Assembly',
    date: '6 days ago',
  },
  {
    name: 'LaQuenda Jackson',
    role: 'Treadmill Repair Customer',
    title: 'Fixed my treadmill in record time',
    review: 'Robbie from 2EZ TEK LLC was amazing! He was very knowledgeable, professional, and incredibly helpful. He fixed my treadmill in record time and made the whole process easy and stress-free. I really appreciated how quickly he diagnosed the issue.',
    tag: 'Treadmill Repair',
    date: '2 weeks ago',
  },
  {
    name: 'Jeff Powell',
    role: 'Local Guide · Repeat Client',
    title: 'Flawless results every single time',
    review: "Robby is easy and effortless to work with. I've used him for a dozen jobs putting together fitness equipment for me. Flawless results each time.",
    tag: 'Assembly',
    date: '3 weeks ago',
  },
  {
    name: 'Jan Cunningham',
    role: 'Treadmill Repair Customer',
    title: 'Better than new treadmill',
    review: 'What could have been a frustrating experience turned into my now having a better than new treadmill. Robby clearly knows machines. He easily but carefully diagnosed and explained what would be involved in the repair which gave me a clear picture of the process.',
    tag: 'Treadmill Repair',
    date: '8 weeks ago',
  },
  {
    name: 'Russell F',
    role: 'Home Equipment Owner',
    title: 'Diagnosed the problem in 5 seconds',
    review: "Amazing, can't say enough great things. Called on Wednesday afternoon, Thursday morning they were here and diagnosed the problem in 5 seconds. Fixed it in 20 minutes, all done.",
    tag: 'Repair',
    date: '12 weeks ago',
  },
  {
    name: 'Sabra Jackson',
    role: 'Local Guide · Treadmill Customer',
    title: 'Outstanding, diagnosed almost immediately',
    review: 'Robby with 2EZ TEK was outstanding. My treadmill suddenly stopped working and I thought it was going to be a major repair, but he diagnosed the issue almost immediately. He explained exactly what was wrong, fixed it quickly, and even showed me maintenance tips.',
    tag: 'Treadmill Repair',
    date: '10 weeks ago',
  },
  {
    name: 'Jack Brown',
    role: 'StairMaster Installation',
    title: 'Exceptional communication start to finish',
    review: 'I had a stairmaster delivered to my house and coordinated with Robby on arrival and he had exceptional communication. He was here as soon as the shipper arrived and he got right to work. He helped unload the stairmaster and brought it in. Outstanding.',
    tag: 'Installation',
    date: '10 weeks ago',
  },
  {
    name: 'Katy Angus',
    role: 'Treadmill Repair Customer',
    title: 'In touch right away, repaired within 5 days',
    review: 'We had a great experience with Robby! He got in touch with me right away. Came out and assessed the issue with our treadmill, knew exactly what was going on, ordered the part and came back to fix it all within 5 days! Very knowledgeable.',
    tag: 'Treadmill Repair',
    date: 'Jul 2024',
  },
  {
    name: 'Kelly Galloway',
    role: 'Local Guide · Precor Owner',
    title: 'Quick, professional, knowledgeable, efficient',
    review: 'Quick to return our call and schedule service. Professional. Personable. Knowledgeable. Helpful. Efficient. GREAT SERVICE! Robby helped us solve our treadmill error codes issues and inspected and performed maintenance on our Precor Treadmill.',
    tag: 'Maintenance',
    date: 'Aug 2023',
  },
  {
    name: 'Rita Adiani',
    role: 'Equipment Repair Customer',
    title: 'Brilliant diagnostics in under 30 mins',
    review: 'Absolutely brilliant diagnostics, service and complete solution delivery! All done in less than 30 mins whilst I waited for an alternative service company to figure it out for over 2 weeks!',
    tag: 'Repair',
    date: 'Jul 2023',
  },
  {
    name: 'Raw Rizo',
    role: 'Bowflex Owner',
    title: 'Repaired my Bowflex in 30 minutes flat',
    review: 'Robby repaired my Bowflex M5 elliptical in 30 minutes flat! He is extremely professional and knowledgeable across the industry. He even let me look over his shoulder and taught me a few things, highly recommended!!',
    tag: 'Repair',
    date: 'Jun 2023',
  },
  {
    name: 'Lucy Catala',
    role: 'Home Equipment Owner',
    title: 'Impeccable work, guaranteed',
    review: "What a fantastic job! Robby was responsive and timely. His work is impeccable. I am glad that I was able to find someone who knew what they were doing and wasn't afraid to guarantee the work. Thank You, Thank You, Thank You!",
    tag: 'Assembly',
    date: 'May 2023',
  },
  {
    name: 'Tony Simons',
    role: 'Treadmill Repair Customer',
    title: 'On the books in less than 12 hours',
    review: "We were impressed with how swiftly 2EZ TEK came to our treadmill's rescue. Less than 12 hours after we'd placed a request, we were on the books for the following day. 2EZ TEK swiftly deduced the problem and helped us through the process.",
    tag: 'Treadmill Repair',
    date: 'Feb 2023',
  },
  {
    name: 'Willean',
    role: 'Equipment Repair Customer',
    title: 'Patient and explains everything clearly',
    review: 'Very patient and explains everything where you can understand the process and issues.',
    tag: 'Repair',
    date: '6 days ago',
  },
  {
    name: 'Billy Marcinko',
    role: 'Local Guide · Gym Assembly',
    title: 'Robby is a beast, highly recommend',
    review: 'Robby is a beast! I highly recommend using him for any kind of gym assembly.',
    tag: 'Assembly',
    date: '41 weeks ago',
  },
  {
    name: 'sean nelson',
    role: 'Rogue Rack Customer',
    title: 'Would recommend 100 times over',
    review: 'Very professional. Called ahead to see if he could come earlier. Highly knowledgeable in setting my Rogue rack system. Would recommend his services a 100 times over and would use again.',
    tag: 'Assembly',
    date: 'Mar 2025',
  },
  {
    name: 'Red Jones',
    role: 'Equipment Assembly Customer',
    title: 'Customer service was immaculate',
    review: 'The customer service was immaculate. My equipment was assembled in a timely manner, I would definitely use again.',
    tag: 'Assembly',
    date: 'Feb 2025',
  },
  {
    name: 'Carrie Grissom',
    role: 'Local Guide · Service Customer',
    title: 'Super professional and friendly',
    review: 'Robby responded promptly to my service request and was quick and efficient once here. He was super professional and friendly. Highly recommend!',
    tag: 'Repair',
    date: 'May 2023',
  },
  {
    name: 'Carmen Estep',
    role: 'Treadmill Assembly Customer',
    title: 'Robby saved the day',
    review: "Robby saved the day! Hubby and I tried to put our new treadmill together with no success. We should have called Robby when we ordered the machine. Robby corrected our mistakes and had it running in no time! Will definitely call him again.",
    tag: 'Assembly',
    date: 'Feb 2023',
  },
  {
    name: 'Daniel McGriff',
    role: 'Local Guide · Boxing Equipment',
    title: 'Excellent job despite limited instructions',
    review: 'Robby was a God send. He came out and set up our Boxing equipment. Did an excellent job even though the instructions were extremely limited. He was on time, efficient and gave some good tips upon leaving.',
    tag: 'Assembly',
    date: 'Aug 2022',
  },
  {
    name: 'Kassandra',
    role: 'Local Guide · NordicTrack Owner',
    title: 'Guru for assembling fitness equipment',
    review: 'Robby is the guru for assembling fitness equipment. Had no issues with my NordicTrack treadmill. Very professional and friendly. I would recommend him for your assembly.',
    tag: 'Assembly',
    date: 'Aug 2022',
  },
  {
    name: 'Shelley Herman',
    role: 'Treadmill Repair Customer',
    title: 'Repaired in less than 20 minutes',
    review: 'I was so happy to find 2EZ TEK to repair my treadmill. Every other company I called put me on a waiting list and said they would call when they had time. Robbie came out within the week and repaired the issue in less than 20 mins.',
    tag: 'Treadmill Repair',
    date: 'Oct 2022',
  },
]

export const GOOGLE_REVIEW_URL = 'https://g.page/r/CQFJm5whu0tLEBM/review'
