import { NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'

const SITE_URL = 'https://www.2eztek.com'

async function triggerAutoBlog(): Promise<{ success: boolean; title?: string; error?: string }> {
  try {
    const res = await fetch(`${SITE_URL}/api/cron/auto-blog`, {
      headers: { Authorization: `Bearer ${process.env.CRON_SECRET}` },
    })
    const data = await res.json()
    if (data.success) return { success: true, title: data.post?.title }
    return { success: false, error: data.error || 'Unknown error' }
  } catch (err: any) {
    return { success: false, error: err.message }
  }
}

export async function GET(request: Request) {
  try {
    const authHeader = request.headers.get('authorization')
    if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
      return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 })
    }

    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!
    )

    // Start of today in CST (UTC-5 / UTC-6 depending on DST; use UTC-6 as conservative)
    const now = new Date()
    const todayCST = new Date(now.toLocaleString('en-US', { timeZone: 'America/Chicago' }))
    todayCST.setHours(0, 0, 0, 0)
    const todayStartUTC = new Date(todayCST.getTime() - todayCST.getTimezoneOffset() * 60000)

    const { data: todayPosts, error: queryError } = await supabase
      .from('blog_posts')
      .select('id, title, created_at')
      .gte('created_at', todayStartUTC.toISOString())
      .eq('published', true)
      .order('created_at', { ascending: true })

    if (queryError) throw new Error(queryError.message)

    const postsToday = todayPosts?.length ?? 0
    const needed = Math.max(0, 2 - postsToday)
    const generated: Array<{ success: boolean; title?: string; error?: string }> = []

    for (let i = 0; i < needed; i++) {
      const result = await triggerAutoBlog()
      generated.push(result)
      if (i < needed - 1) await new Promise((r) => setTimeout(r, 5000))
    }

    const allOk = generated.every((r) => r.success)
    const subject =
      needed === 0
        ? `Daily Audit: All ${postsToday} blog posts published on schedule`
        : allOk
          ? `Daily Audit: Self-healed ${generated.length} missed blog post${generated.length > 1 ? 's' : ''}`
          : `Daily Audit: WARNING — ${generated.filter((r) => !r.success).length} blog post(s) failed to generate`

    if (process.env.RESEND_API_KEY) {
      const rowStyle = 'padding:8px 12px;border-bottom:1px solid #eee;'
      const generatedRows = generated
        .map(
          (r) =>
            `<tr><td style="${rowStyle}">${r.success ? '✅' : '❌'}</td><td style="${rowStyle}">${r.title || r.error || '—'}</td></tr>`
        )
        .join('')

      await fetch('https://api.resend.com/emails', {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${process.env.RESEND_API_KEY}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          from: '2EZ TEK <support@2eztek.com>',
          to: ['support@2eztek.com'],
          subject,
          html: `
            <div style="font-family:Arial,sans-serif;line-height:1.6;color:#111;max-width:600px">
              <h2 style="color:#0891B2">Nightly Blog Audit Report</h2>
              <p><strong>Date:</strong> ${now.toLocaleDateString('en-US', { timeZone: 'America/Chicago', weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })} CST</p>
              <p><strong>Posts published today:</strong> ${postsToday}</p>
              <p><strong>Target:</strong> 2 per day</p>

              ${
                postsToday > 0
                  ? `<h3>Today's Posts</h3>
                     <table style="width:100%;border-collapse:collapse;border:1px solid #eee;">
                       ${(todayPosts ?? []).map((p) => `<tr><td style="${rowStyle}">✅</td><td style="${rowStyle}">${p.title}</td></tr>`).join('')}
                     </table>`
                  : ''
              }

              ${
                generated.length > 0
                  ? `<h3>${allOk ? '🔧 Self-Healed' : '⚠️ Recovery Attempt'}</h3>
                     <table style="width:100%;border-collapse:collapse;border:1px solid #eee;">
                       ${generatedRows}
                     </table>`
                  : ''
              }

              <hr/>
              <p style="color:#666;font-size:13px">Auto-generated by 2EZ TEK Daily Audit. Runs nightly at midnight CST.</p>
            </div>
          `,
        }),
      })
    }

    return NextResponse.json({
      success: true,
      postsToday,
      needed,
      generated,
    })
  } catch (error: any) {
    console.error('DAILY AUDIT ERROR:', error)
    return NextResponse.json({ success: false, error: error.message }, { status: 500 })
  }
}
