import { NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import { callClaude, cleanJsonOutput } from '@/lib/claude'

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'

const SOCIAL_SYSTEM = `You are a social media copywriter for 2EZ TEK, a fitness equipment repair company in Dallas Fort Worth, TX.

Write engaging Instagram and Facebook captions that feel authentic and local — not corporate. 2EZ TEK fixes treadmills, ellipticals, bikes, and gym equipment for homes and commercial facilities across DFW.

Rules:
- Instagram: punchy opener, 2-3 lines of copy, 5-8 relevant hashtags. Max 220 characters before hashtags.
- Facebook: slightly longer, conversational, no hashtags needed, ends with soft CTA
- Tone: knowledgeable local tech, proud of the craft, helpful — NOT salesy
- Include the phone number (972) 807-7232 in at least one post
- Never guarantee same-day service or specific prices
- Return ONLY valid JSON: { "instagram": "", "facebook": "" }`

type BlogPost = {
  id: string
  title: string
  content: string
  slug: string
  created_at: string
}

async function generateSocialPosts(source: BlogPost): Promise<{ instagram: string; facebook: string }> {
  const excerpt = source.content.replace(/<[^>]*>/g, '').slice(0, 600)

  const userMessage = `Generate Instagram and Facebook captions based on this 2EZ TEK content.

Title: ${source.title}
Content excerpt: ${excerpt}

Return ONLY valid JSON: { "instagram": "", "facebook": "" }`

  const outputText = await callClaude({
    system: SOCIAL_SYSTEM,
    userMessage,
    maxTokens: 600,
    temperature: 0.75,
  })

  return JSON.parse(cleanJsonOutput(outputText))
}

function buildSummaryEmail(posts: Array<{ title: string; instagram: string; facebook: string }>): string {
  const sections = posts.map((p, i) => `
    <div style="margin-bottom:28px;padding:20px;border:1px solid #e5e5e5;border-radius:12px">
      <h3 style="margin:0 0 12px;color:#0891B2">Post ${i + 1}: ${p.title}</h3>
      <p style="font-weight:bold;margin:0 0 4px">Instagram:</p>
      <p style="white-space:pre-wrap;background:#f9fafb;padding:12px;border-radius:8px;font-size:14px">${p.instagram}</p>
      <p style="font-weight:bold;margin:12px 0 4px">Facebook:</p>
      <p style="white-space:pre-wrap;background:#f9fafb;padding:12px;border-radius:8px;font-size:14px">${p.facebook}</p>
    </div>
  `).join('')

  return `
    <div style="font-family:Arial,sans-serif;line-height:1.6;color:#111;max-width:680px">
      <h2 style="color:#0891B2">Weekly Social Media Posts — 2EZ TEK</h2>
      <p>Here are this week's ready-to-post captions. Copy and paste into Instagram/Facebook.</p>
      ${sections}
      <hr/>
      <p style="color:#666;font-size:13px">Auto-generated by 2EZ TEK Social Post Engine. Runs weekly on Wednesdays.</p>
    </div>
  `
}

export async function GET(request: Request) {
  try {
    const authHeader = request.headers.get('authorization')
    if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
      return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 })
    }

    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!
    )

    // Pull 3 recent blog posts to generate posts from
    const { data: posts, error } = await supabase
      .from('blog_posts')
      .select('id, title, content, slug, created_at')
      .eq('published', true)
      .order('created_at', { ascending: false })
      .limit(3)

    if (error) throw new Error(error.message)
    if (!posts || posts.length === 0) {
      return NextResponse.json({ success: true, message: 'No blog posts available for social content', generated: 0 })
    }

    const generated: Array<{ title: string; instagram: string; facebook: string }> = []

    for (const post of posts as BlogPost[]) {
      try {
        const { instagram, facebook } = await generateSocialPosts(post)
        generated.push({ title: post.title, instagram, facebook })
        await new Promise((r) => setTimeout(r, 500))
      } catch (err) {
        console.error('Social post generation failed for:', post.title, err)
      }
    }

    if (!process.env.RESEND_API_KEY || generated.length === 0) {
      return NextResponse.json({ success: true, generated: generated.length, posts: generated })
    }

    await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${process.env.RESEND_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: '2EZ TEK <support@2eztek.com>',
        to: ['support@2eztek.com'],
        subject: `Weekly Social Posts — ${generated.length} ready to publish`,
        html: buildSummaryEmail(generated),
      }),
    })

    return NextResponse.json({ success: true, generated: generated.length })
  } catch (error: unknown) {
    console.error('SOCIAL POSTS CRON ERROR:', error)
    return NextResponse.json(
      { success: false, error: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    )
  }
}
